-- Seed data for LeidenCS.
-- Generated from the Leiden University study guide 2025-2026.
-- Run `python3 scripts/scrape_studiegids.py --refresh` to update from source pages.

insert into public.specializations (code, name, study_id) values
  ('acs', 'Advanced Computing and Systems', '10550'),
  ('ai', 'Artificial Intelligence', '10551'),
  ('bioinf', 'Bioinformatics', '10552'),
  ('cse', 'Computer Science and Education', '10553'),
  ('scss', 'Computer Science and Science Communication and Society', '10554'),
  ('ds', 'Data Science', '10555'),
  ('foc', 'Foundations of Computing', '10556'),
  ('csbs', 'Computer Science and Business Studies', '10602')
on conflict (code) do update
set name = excluded.name,
    study_id = excluded.study_id;

insert into public.courses (code, title, description, studiegids_url, color, icon, ec) values
  ('4343ADVDX', 'Advances in Data Mining', 'The traditional data mining techniques are mainly focused on solving classification, regression and clustering problems. However, the recent developments in ICT led to the emergence of new sorts of massive data sets and related data mining problems. Consequently, the field of data mining has rapidly expanded to cover new areas of research, such as: real-time analysis of data streams (internet traffic, sensor data, electronic transactions, etc.),', 'https://studiegids.universiteitleiden.nl/en/courses/131394/advances-in-data-mining', '#06b6d4', 'chart', 6),
  ('4343AIART', 'AI and Art', 'This course examines the evolving intersection where machine learning meets artistic expression. AI is increasingly present in daily life—and art is no exception, from museum installations to machine-driven aesthetics. Today’s AI systems not only generate images, music, and poetry, but also critique artistic work—bringing new debates about creativity, authorship, and aesthetic judgment. These developments spark both excitement and skepticism, raising important philosophical and ethical questions: What does it mean for a machine to create or critique art? And more fundamentally, what is art? Blending different perspectives, we will discuss the place of AI in the art world. This course teaches the models and methods behind AI-generated art: how they work, why they matter, and their potential future directions. We will examine the technical background of generative systems, along with their', 'https://studiegids.universiteitleiden.nl/en/courses/135824/ai-and-art', '#ec4899', 'book-open', 6),
  ('4343AISOC', 'AI in Society', 'With the rapid development of AI technologies, many are concerned about their impact on the world. This course explores the questions of social and technological change, ethics and the responsibilities associated with it, and invites students to speculatively re-imagine the kind of world and AI technologies we would like to have. AI in Society offers a critical, societal perspective on artificial intelligence and explores how technical decisions concerning data, methods, and tools affect individuals and communities worldwide in many different ways.', 'https://studiegids.universiteitleiden.nl/en/courses/131636/ai-in-society', '#8b5cf6', 'book-open', 6),
  ('4343APQALY', 'Applied Quantum Algorithms', 'Quantum computing is an upcoming technology which is expected to have game-changing applications in all computationally-intensive branches of the natural sciences; material sciences, chemistry and physics. Resource-efficient algorithm design is an essential step towards making quantum computers viable for these applications. This is an advanced course for students with understanding of the basics of quantum computing (e.g. for students which have taken Quantum Algorithms at LIACS or Quantum Information at LION), that emphasises practical quantum computing for potential near-term applications. In this course, you will learn about modern quantum algorithmic techniques, and how they are applied in quantum chemistry, quantum many-body physics and machine learning. Furthermore, you will learn about the fundamentals of quantum error correction and error mitigation techniques required to make n', 'https://studiegids.universiteitleiden.nl/en/courses/131620/applied-quantum-algorithms', '#6366f1', 'atom', 6),
  ('4383ARCR3', 'Artificial Creatures', 'Intelligent robots are all the rage nowadays, but what about emotional robots? And creative robots? Or even useless, curious, helpless or misbehaving robots? Does researching these bots with ''unique'' human or lifelike qualities make us less or more human? And why should we care? In this course we discuss inspirational examples demonstrating that bots can be more than just smart, and argue that by studying bots like you we can learn more about who we are as humans, and speculate about our joint future.', 'https://studiegids.universiteitleiden.nl/en/courses/131637/artificial-creatures', '#d946ef', 'book-open', 3),
  ('4343AUDIO', 'Audio Processing and Indexing', 'During this seminar the fundamentals of audio processing and indexing will be studied. Applications in the area of speech recognition and understanding, audio synthesis and content based audio retrieval will be discussed. State of the art work on speech recognition, speech synthesis and content based audio retrieval will be studied and presented by the participants. The seminar starts with several lectures and accompanying assignments in the form of workshops; followed by a literature selection, study, and presentations by all the students; the seminar ends with final project demos / presentations.', 'https://studiegids.universiteitleiden.nl/en/courses/131607/audio-processing-and-indexing', '#3b82f6', 'book-open', 6),
  ('4343AUTMX', 'Automated Machine Learning', 'The fields of Data Science and Machine Learning deal with large volumes of data. Complex algorithms such as stochastic gradient descent, gradient boosting and support vector machines are able to model this data and make predictions about future trends. Most of these algorithms have a high number of hyperparameters, that need to be tuned correctly for the resulting model to perform well. Properly tuned hyperparameters can determine the difference between mediocre performance and state-of-the-art performance. When presented with a new dataset, common problems that need to be addressed are: Which algorithm to use and how to tune the hyperparameters to obtain good predictive performance. The research field of Automated Machine Learning (AutoML) focuses on how to automate this process.', 'https://studiegids.universiteitleiden.nl/en/courses/131608/automated-machine-learning', '#8b5cf6', 'brain', 6),
  ('4343BAYOP', 'Bayesian Optimization', 'This course covers the fundamentals of optimization, focusing on Bayesian optimization (BO) methods for optimizing expensive-to-evaluate functions in continuous search spaces. It introduces Gaussian processes as surrogate models and discusses various acquisition functions for balancing exploration and exploitation. The course includes practical implementation using Python libraries and real-world applications like applications in engineering and hyperparameter tuning. Advanced topics such as handling noisy observations and optimization on mixed-integer/discrete and/or constrained spaces are also explored. This course is unique in its nature. While some universities around the world have offered seminars on BO (due to the increasing popularity of these algorithms for optimizing expensive-to-evaluate processes), we are the first to provide a comprehensive course on the topic. The course of', 'https://studiegids.universiteitleiden.nl/en/courses/131609/bayesian-optimization', '#10b981', 'book-open', 6),
  ('4343BIOMD', 'Bio-Modeling', 'In order to systematically investigate biological systems, experimental and computational approaches can be combined. To understand a biological system, structural and dynamic properties can be represented in a computational model describing the entities involved and their interactions. This course aims at making students aware of formal and mathematically precise approaches to the faithful modeling of biological processes. In an interdisciplinary approach we will investigate how to construct and analyze such formal models using the frameworks of Boolean Networks and Petri nets. Biological case studies will be used as a guide to the modelling of biological phenomena.', 'https://studiegids.universiteitleiden.nl/en/courses/131525/bio-modeling', '#84cc16', 'dna', 6),
  ('4343BICAI', 'Brain-inspired Computing for AI', 'How can we make AI as efficient as the human brain? This course explores how to achieve energy-efficient AI by drawing inspiration from the brain, one of the most powerful and low-power intelligent systems known. As deep learning models like large language models (LLMs) continue to grow in size and complexity, running them efficiently on edge devices (such as smartwatches and VR headsets) and at scale is becoming an urgent challenge. In this course, students will learn and explore a range of cutting-edge techniques for efficient AI, including model compression like pruning, quantization, and neuromorphic computing. We also explore the hardware frontier, examining how modern AI processors are optimized to support low-power, high-performance machine learning.', 'https://studiegids.universiteitleiden.nl/en/courses/135825/brain-inspired-computing-for-ai', '#7c3aed', 'book-open', 6),
  ('4343BSCC4', 'Capstone Cases', 'The Capstone cases course is intended to integrate the previous courses and allow students to deepen and apply their insights in a ‘Living Case’, i.e. applying it to solving a real problem in a real company. The course consists of introductory lectures and two real life capstone case projects for the students to complete. Only after finishing 2 capstone projects + the introductory lectures the student receives his/her grade. Ideally this takes 2 semesters in total.', 'https://studiegids.universiteitleiden.nl/en/courses/131668/capstone-cases', '#001158', 'book-open', 4),
  ('4343CICSX', 'Causal Inference for Computer Scientists', 'In the field of machine learning, you may need to predict the impact of an action on an outcome by analyzing a huge amount of collected data. Unfortunately, this data is often of low quality, with missing records, unobserved confounders, and selection biases. As a result, answering questions about the impact of an action becomes more difficult than ever. This course covers mathematical tools to help you perform causal inference in big data. We will use structural causal models, and potential outcomes to formalize what causal effects mean, explain how to express these effects as functions of observed data, and use machine learning techniques to estimate them. We will also cover causal structure learning algorithms to recover causal relationships from data, and discuss applications of causality in other fields in machine learning (such as reinforcement learning and natural language process', 'https://studiegids.universiteitleiden.nl/en/courses/131621/causal-inference-for-computer-scientists', '#14b8a6', 'book-open', 6),
  ('4343CLCMX', 'Cloud Computing', 'Easily accessible and responsive web-based services play a prominent role in modern society. Examples include data storage (documents, photos, etc.), content delivery (video streaming), social media, mapping and route planning, document editing and traditional web sites. Many of these services are empowered by cloud infrastructure. In the last decade, we have witnessed a large-scale transition from systems and software managed "on-premises" to infrastructure and software run in the cloud. Adoption of the cloud is expected to continue to increase in the coming years. Academic interest in the cloud is twofold. Firstly, Cloud Computing is a multidisciplinary area of research involving issues in theory, algorithms, computer systems, performance measurement and modeling, and middleware and application design. Secondly, the use of the cloud as a platform within which to conduct research is inc', 'https://studiegids.universiteitleiden.nl/en/courses/131602/cloud-computing', '#0ea5e9', 'cloud', 6),
  ('4609COMNWY', 'Complex Networks (BM)', 'Transportation, traffic, energy, communication and social networks form the backbone of modern society. In recent years, there has been a growing fascination with the complex “connectedness” that such networks provide. This connectedness manifests itself in many ways: in the rapid growth of the Internet and the World Wide Web, in the ease with which global communication takes place, in the speed at which news and information travels around the world, and in the spread of an epidemics or a financial crisis. These phenomena are based on the links that connect people and their decisions, and have global consequences. The course aims to provide students with a concise introduction into this lively area, and covers both theoretical principles and practical applications from a variety of different directions. Complex Networks is a multi-disciplinary course: it exposes views on Complex Networks', 'https://studiegids.universiteitleiden.nl/en/courses/131371/complex-networks-bm', '#2563eb', 'network', 6),
  ('4383COMCR', 'Computational Creativity', 'Computational Creativity is a subfield of Artificial Intelligence concerned with the philosophy, science and engineering of computational systems exhibiting behaviours that may be judged to be creative. In this course we will explore approaches to the computational modelling of creativity as well as the theories of human creativity that have informed them. We will explore computational models of creative processes, e.g., analogy-making, models of creative individuals, e.g., creative agents, and simulations of creative societies, e.g., multi-agent models. We will explore different approaches to developing autonomous creative systems, as well as, collaborative, i.e., co-creative, systems. We will discuss fundamental questions of what it means for a machine to be creative, how computational creativity can be evaluated and the implications for human creativity.', 'https://studiegids.universiteitleiden.nl/en/courses/131610/computational-creativity', '#f43f5e', 'book-open', 6),
  ('4343CIMTO', 'Computational Imaging and Tomography', 'Computational imaging concerns the computation of images from various types of physical measurements, using computationally intensive algorithms. It typically involves aspects from physics (modelling the measurements), mathematics (modelling the inverse problem), and computer science (algorithms and high-performance computing). A famous example of computational imaging is tomography, where a 3D image of an object is formed by acquiring a series of projection images (i.e. X-ray photos) from a range of angles, and then computing the image through a series of algorithmic steps. In this seminar course, the topics of computational imaging and tomography will be introduced in lectures, after which a series of more advanced topics will be treated by studying research papers. The introduction part covers:', 'https://studiegids.universiteitleiden.nl/en/courses/131622/computational-imaging-and-tomography', '#0ea5e9', 'book-open', 6),
  ('4343CMS6X', 'Computational Models and Semantics', 'Computing systems become increasingly more complex and handle a variety of different tasks. As our society relies on these systems working correctly, we need formal descriptions of computational models and semantics of programming languages to be able to verify the correctness of computing systems. The computational models that we will study in this course range from the simplest functional model to probabilistic models that underpin statistical phenomena in optimisation and machine learning. During the course, we will introduce several programming language, all coming with specific kinds of computational models that allow us to give semantics to these languages. This approach allows us to concretely understand the purpose of the corresponding computational model, while we can use the languages to write and run concrete programs. We will find that this variety of computational models and', 'https://studiegids.universiteitleiden.nl/en/courses/131611/computational-models-and-semantics', '#3b82f6', 'book-open', 6),
  ('4433COMST', 'Computational Statistics', 'This course will introduce you to the field of computational statistics, which can be loosely defined as a set of numerical methods and algorithms that can be employed to solve a well-defined statistical problem. We will discuss the mathematical and statistical foundations that such methods rely on, and show how you can implement them in R. The course will cover the following topics: 1. Methods for the generation of random variables 2. The Monte Carlo method 3. Applications of the Monte Carlo method 4. Variance reduction methods 5. Numerical integration and root finding algorithms 6. The bootstrap 7. Applications of the bootstrap 8. Permutation tests', 'https://studiegids.universiteitleiden.nl/en/courses/131643/computational-statistics', '#06b6d4', 'chart', 3),
  ('4343CRYPE', 'Cryptographic Engineering', 'One part of this course will concentrate on the implementation aspects of cryptographic algorithms and protocols. Design constraints on resource utilization, energy consumption and performance will be taken into account in the design of cryptographic hardware and software. Another part of the course explains how attacks can be mounted that specifically target weaknesses in the implementation of the cryptographic algorithms. Countermeasures against these implementation attacks and their effect on the resource utilization, the energy consumption and the performance will also be covered in the course.', 'https://studiegids.universiteitleiden.nl/en/courses/131603/cryptographic-engineering', '#e11d48', 'shield', 6),
  ('4343BSCSM', 'Cyber Security Management', 'If you ask the modern CIO what keeps him awake at night, You expect that next to profit and innovation, ICT security will invariably be in his top-3 of worries. This course is NOT a technical course (of all 6 course blocks, only one block is “technical”). It aims at providing the student in a future role of CIO or ICT consultant with enough knowledge to: Understand the full scope of ICT security;', 'https://studiegids.universiteitleiden.nl/en/courses/131665/cyber-security-management', '#9f1239', 'shield', 3),
  ('4343DASPR', 'Data Science in Practice', 'This course prepares students for application of data science in real-life settings. Students work in Fieldlabs on real data problems. The students will explore the data-problem, research data availability, investigate the quality of the data and design a solution for the problem. Students work in teams, which are called Fieldlabs. They receive support from coaches who are cognisant of the data-problem and the context of it. In the lectures the students will receive practical tools that can be deployed for a solution that addresses the problem. The Fieldlab will be addressing data architectures which are federated, with localised repositories, making use of linked, semantic data curation techniques to achieve data-interoperability based on RDF. Materials will be provided during the course.', 'https://studiegids.universiteitleiden.nl/en/courses/131644/data-science-in-practice', '#059669', 'chart', 6),
  ('4433DATVI', 'Data Visualization', 'Data visualizations give viewers insight in data patterns and are therefore an integral part of data analysis and the communication of statistical results. Hence, applied statisticians and other researchers should learn how to visualize their data in an effective and perceptually accurate manner such that the plots correctly convey the data message. Additionally, they should be able to visualize the statistical models fitted on data and these models’ uncertainty, so that they can easily be interpreted by users. In this course you will learn about the principles of effective data visualizations and how to apply them. Furthermore, you will learn how to make explorative data visualizations and how to visualize uncertainty. In this course all plots are made in R (mainly with the ggplot2 package) in a reproducible way (R Markdown).', 'https://studiegids.universiteitleiden.nl/en/courses/131645/data-visualization', '#f59e0b', 'chart', 6),
  ('4343DDORW', 'Data-driven optimisation for Real-World Applications', 'In this course, students will learn to design and implement optimization models that incorporate real-world complexity, uncertainty, and available data (including historical and real-time data). We will introduce theoretical foundations through practical applications. Students will explore how to model real-world problems and integrate learning methods into optimization to manage dynamic and uncertain environments, as well as to balance multiple, often conflicting objectives. The course begins with foundational concepts in optimization, followed by real-world case studies in domains such as logistics, supply chains, and energy systems. Students will systematically learn to model and solve complex decision problems involving stochasticity, robustness, multi-objective trade-offs, and human behavioral considerations. Key topics include stochastic programming, robust optimization, multi-obje', 'https://studiegids.universiteitleiden.nl/en/courses/135826/data-driven-optimisation-for-real-world-applications', '#10b981', 'chart', 6),
  ('4343BSDPM', 'Data-driven Policy Making', 'New concepts try to grasp the way the public realm is working with data, such as the ‘Data Readiness Concept’ and ‘Digital-era Governance’. They are built on the assumption that data- and technology-driven innovations in government need an infrastructure for creating value from data and closely linked to the e-government idea of technologies transforming government towards being more responsive and accountable. The course will unravel these more recent concepts and connect them to the existing concept of evidence-based policymaking and the literature on e-government and new public management. Taken together, these approaches to data-based policymaking carry different labels, but they converge on several themes. First, the idea that government entities require the capacity, skills and data culture to deal with this type of evidence. Second, the role of data in policymaking, where governme', 'https://studiegids.universiteitleiden.nl/en/courses/131673/data-driven-policy-making', '#001158', 'chart', 6),
  ('4343DISYX', 'Distributed Systems', 'Distributed systems are pervasive, and most members of our society interact with them daily. Social networks, government services, and media streaming are all powered by distributed systems. Such systems are composed of many physically distributed computers, all connected through a network. Distributed systems are applied in areas such as data storage (e.g., HDFS, Ceph), data transmission and queueing (e.g., gRPC, ZeroMQ), key-value stores (e.g., Redis, Cassandra), analytics (e.g., Spark, Hive), batch (e.g., MapReduce, Hadoop) and stream processing (e.g., Flink), distributed supercomputing (e.g., MPI), as well as machine learning (e.g., Tensorflow, pytorch). As computer scientists, systems engineers, or devops, most of the large-scale systems we work with, either directly or indirectly, are actually distributed systems. Both academia and industry invest significant effort into: (i) defin', 'https://studiegids.universiteitleiden.nl/en/courses/131623/distributed-systems', '#f97316', 'cloud', 6),
  ('4343EMBSS', 'Embedded Systems and Software', 'Embedded Systems are application domain specific information processing systems that are tightly coupled to their environment. They appear in home appliances, copy machines, automotive entertainment systems, medical imaging systems, wireless and portable multimedia terminals, distributed sensor networks, and more. The course first introduces the notion of and some basic concepts in embedded systems and software. Then it deals with basic methods, techniques, algorithms, and components that are found in embedded systems.', 'https://studiegids.universiteitleiden.nl/en/courses/131604/embedded-systems-and-software', '#ea580c', 'code', 6),
  ('4343BSEA6', 'Enterprise Architecture', 'This course is about the process and techniques to create an enterprise architecture for an organization. An enterprise architecture is a coherent whole of principles, methods and models that are used in the design and realisation of an enterprise’s organisational structure, business processes, information systems, and infrastructure. It represents a long term view that help organizations to guide the development of their IT over a longer period of time. An important objective of enterprise architecture is to align the IT strategy with the business strategy and improve organizational efficiency and agility. Therefore the course also covers business and IT strategy, and strategic alignment. Following that the methods and modelling techniques for enterprise architecture are covered. We will use the ArchiMate modelling language to model an enterprise architecture.', 'https://studiegids.universiteitleiden.nl/en/courses/131667/enterprise-architecture', '#64748b', 'book-open', 6),
  ('4343EVALX', 'Evolutionary Algorithms', 'Evolutionary Computation is a field of computer science dealing with algorithms gleaned from the model of organic evolution – so-called evolutionary algorithms. The idea is to let the computer evolve solutions to problems rather than trying to “calculate” them. Evolutionary algorithms do this by using the fundamental principles of evolution such as, for example, selection, mutation and recombination among a population of simulated individuals. The evolutionary approach is used today in a variety of application areas for solving problems that require intelligent behaviour, adaptive learning and optimization. These fields include e.g. engineering optimization, artificial life, automatic programming, autonomous agents, and machine learning, since optimization algorithms are a core component of many machine learning approaches.', 'https://studiegids.universiteitleiden.nl/en/courses/131526/evolutionary-algorithms', '#8b5cf6', 'book-open', 6),
  ('4433EXPDA', 'Exploratory Data Analysis', 'Studying the relationship between two (or maybe three) variables is easy; you can visualise them in two-dimensional (or maybe three-dimensional) graphs. However, when you are interested in the relationship between more than three variables, the human brain often falls short and you need specialised methods to get more insight in the dependencies between either cases or variables, even more so if the relations are not linear. Many of these specialised methods include the option to transform data in order to explore any non-linear relationships and to reduce the dimensionality. Additionally, these methods allow for a mix of different types of variables, continuous or categorical. These models are generally data-driven and therefore descriptive in nature, but some statistical inference can be done.', 'https://studiegids.universiteitleiden.nl/en/courses/131646/exploratory-data-analysis', '#0ea5e9', 'chart', 6),
  ('4343FSWT6', 'Foundations of Software Testing', 'Software testing is the process of executing a program with the intent of identifying failures. Most software faults stem from design errors, not due to the quality of programmers, but because the complexity of software is increasingly becoming intractable. Testing is a vital technique used in the validation and verification of software systems. This course provides an introduction to the foundations of software testing without adhering to a specific methodology or technology. We will address three key problems related to testing:', 'https://studiegids.universiteitleiden.nl/en/courses/131625/foundations-of-software-testing', '#2563eb', 'code', 6),
  ('4383HICNM', 'From Human Intelligence to Cognition in Nature and Machines', 'Recent advances in AI have seen remarkable progress, with unprecedented improvements on many complex tasks. This has in turn resulted in a massive increase in speculations on what such novel systems might be capable of, up to the point where even an AI engineer believed their own technology had become sentient or conscious. This raises more basic questions such as what it actually means to be sentient or conscious in both humans and non-humans and how non-humans can be properly tested for fundamental aspects of human thinking. These kinds of questions have been studied extensively for decades in the fields of animal cognition, which investigates the mental processes and abilities of non-human animals. By exploring the depths of human, animal and machine cognition research, this course aims to inspire students to think beyond conventional testing methods, and critically evaluate the devel', 'https://studiegids.universiteitleiden.nl/en/courses/131716/from-human-intelligence-to-cognition-in-nature-and-machines', '#7c3aed', 'book-open', 6),
  ('4343BSGBG', 'Global Business Game - CIO Simulation', 'Kick off course: a first general acquaintance with managing a company by playing a management simulation game.', 'https://studiegids.universiteitleiden.nl/en/courses/131662/global-business-game-cio-simulation', '#001158', 'book-open', 0),
  ('4343HIPX6', 'High Performance Computing', 'This course provides a robust introduction to the world of High Performance Computing (HPC). Starting with a review of trends in supercomputer architectures, the course covers distributed computing, shared memory programming, and GPU programming and optimization. We conclude with an exploration of current research topics, such as auto-tuning, mixed-precision computing, and the intersection of HPC and AI.', 'https://studiegids.universiteitleiden.nl/en/courses/131605/high-performance-computing', '#ef4444', 'book-open', 6),
  ('4433HDDAN', 'High-dimensional data analysis', 'Modern day high-throughput techniques characterize many traits (easily thousands) of an individual simultaneously. Often the resulting data are available for a comparatively small number of individuals. This unbalance in number of covariates to the sample size is typical to high-dimensional data. Such data arise in genomics, where genetic information is measured for many thousands of genes simultaneously, but also in economics and psychometrics. Analysis of high-dimensional data requires adjustments to well-known statistical methods, and the introduction of several novel concepts. The course teaches students the adjustments to classical statistical methodology necessary to analyse high-dimensional data. This encompasses estimation methods, testing procedures, and shrinkage. More specifically, a) model-based inference for Gaussian and count data (classical and Bayesian methods); b) multip', 'https://studiegids.universiteitleiden.nl/en/courses/131638/high-dimensional-data-analysis', '#14b8a6', 'chart', 6),
  ('4343BSICT', 'ICT Enabled Process Innovation', 'The course ICT enabled process innovation will focus on the role of processes and process thinking in organizations with respect to ICT. Information and Communication technologies can radically change the way companies are carrying out their business. Yet, implementing the latest system alone is not the magic pill for business success. On the contrary, process innovation starts with a thorough understanding of the strategy, process and structure of an organization before the right ICT technology can be selected and implemented. To further complicate matters most ICT driven organizations and environments have a tendency to change continuously adding additional complexity to ICT enabled process innovation. Process thinking is correctly considered as one of the most important approaches to performance improvement. It is the precondition for the quality standards of the new ISO 9000:2000 ser', 'https://studiegids.universiteitleiden.nl/en/courses/131664/ict-enabled-process-innovation', '#001158', 'book-open', 3),
  ('4343MMAV6', 'Image Analysis with Applications in Microscopy', 'Microscopy images are typically good material to learn about image processing and analysis. In this course the origin and analysis of images acquired through microscopy is the leading theme. Images play a major role in understanding of all kind of processes and phenomena. The principles of image formation, processing and analysis are however generic. For biomedical research Bio-molecular processes are visualized by a range of microscopical techniques and modalities. From images coherent visualizations and models are derived. The characteristic sequence of image analysis starts with the acquisition, proceeds to restoration and segmentation to conclude with analysis. This sequence will be the skeleton of this course. Image acquisition in microscopy will be dealt with on a theoretical as well as practical level. In a series of lectures all important aspects of imaging along the line of the ', 'https://studiegids.universiteitleiden.nl/en/courses/131524/image-analysis-with-applications-in-microscopy', '#84cc16', 'dna', 6),
  ('4343INFRX', 'Information Retrieval', 'The internet, search engines, and large language models have drastically changed the way humans deal with information. Whereas in the previous century librarians were still classifying books and articles using subject codes, nowadays search technology is available to everyone, everywhere, and in many different contexts. We all use search engines on a daily basis to find relevant information. Not only on the web (e.g. with a search engine or chatGPT), but also in e-commerce websites, social media and news platforms, travel portals, video/music apps, and our email clients. This course covers both the theory and practice of the field of Information Retrieval, with a focus on textual content. Outline: Fundamentals: week 1. Introduction to retrieval and ranking week 2. Boolean retrieval, indexing and compression week 3. Evaluation and test collections', 'https://studiegids.universiteitleiden.nl/en/courses/131626/information-retrieval', '#0ea5e9', 'chart', 6),
  ('4343ITDM6', 'Information Theoretic Data Mining', 'How can we gain insight from data? How can we discover and explain structure in data if we don''t know what to expect? What is the optimal model for our data? How do we develop principled algorithms for exploratory data mining? To answer these questions, we study and discuss the state of the art in the research area of information theoretic data mining. We focus on theory, problems, and algorithms; not on implementation and experimentation. Over the last decade, information theoretic methods for selecting the best model have become popular in the academic data mining community. This course provides an overview of the use of information theory for exploratory data mining, with a focus on pattern-based modelling. This includes the theoretical foundations, modelling and model selection, and algorithms.', 'https://studiegids.universiteitleiden.nl/en/courses/131627/information-theoretic-data-mining', '#10b981', 'chart', 6),
  ('4343INDLX', 'Introduction to Deep Learning', 'The course provides an introduction to key concepts, algorithms, and architectures for neural networks, with strong emphasis on Deep Learning and its application on computer vision / image processing. Topics include: Deep neural network architectures', 'https://studiegids.universiteitleiden.nl/en/courses/131395/introduction-to-deep-learning', '#4f46e5', 'brain', 6),
  ('4343IRPRJ', 'Introductory Research Project (Bioinformatics)', 'A research project deals with research and innovation. It is not as extensive as a Master''s thesis research project, but it serves as a good introduction to managing and conducting scientific research. The research project is open to students following the Bioinformatics specialisation, under the supervision of a research staff member at LIACS. Research can be conducted at Leiden University, or as part of an internship at another institution or company. Research projects are typically scientific projects which are smaller in scope than a thesis, but they could also involve extending and improving an algorithm, conducting systematic tests and comparisons between methods, or writing a survey article covering the latest developments in a field. Topics can be proposed by students or staff, but the research project can only begin after the research project has been approved by the study advis', 'https://studiegids.universiteitleiden.nl/en/courses/131640/introductory-research-project-bioinformatics', '#22c55e', 'dna', 18),
  ('4433LGMO6', 'Linear and Generalized Linear Models', 'In the study of the effect of one or more explanatory variables on a response variable, linear regression and analysis of variance are important techniques. In linear regression we study how a quantitative variable, like the dose of a medicine, influences a quantitative response variable, like blood pressure. In analysis of variance we compare different groups with respect to a quantitative response, e.g. comparing the yields of different corn varieties. The statistical models that underlie these techniques are special cases of the linear model. Although linear models are widely used, sometimes alternatives are preferred. Therefore, we discuss how to check the assumptions underlying linear model: independent errors, with a normal distribution and constant variance. When the assumptions of normality and constant variance are violated, the wider class of generalized linear models may be em', 'https://studiegids.universiteitleiden.nl/en/courses/131647/linear-and-generalized-linear-models', '#0ea5e9', 'book-open', 6),
  ('4343BSMLB', 'Machine Learning for Business Analytics', 'Many decisions in business and government are taken on the basis of data that come from all sorts of information sources. Business Analytics (BA) is about the use of the information stored in this data to generate new and useful knowledge that can support executive managers and governments in taking decisions. The interest in BA is growing due to the increasing awareness of companies and governments that the vast amounts of data collected on humans and their behaviour contain valuable information. The volume of the collected data enables the use of Machine Learning methods to ‘learn’ the relevant knowledge related to the business question. Different types of knowledge can then be derived from the ‘learned’ models, like rules characterising potential customer classes, knowledge classifying groups with larger risks, and so on. Quite often useful causal relations are hidden in the data and ', 'https://studiegids.universiteitleiden.nl/en/courses/131542/machine-learning-for-business-analytics', '#f59e0b', 'brain', 3),
  ('4343BSMSE', 'Managing Software Evolution', 'For most businesses and governmental organizations, the cost and effort of continued development and maintenance of software technology far exceeds the investment in its initial development. In this course, we explore the fundamental forces that drive software evolution and we discuss techniques for managing software evolution, including measurement and monitoring of software quality and architecture, application portfolio management, and software risk assessment. You will have the opportunity to apply such techniques by carrying out a number of management tasks on software development activities of students in other courses.', 'https://studiegids.universiteitleiden.nl/en/courses/131671/managing-software-evolution', '#2563eb', 'code', 3),
  ('4343MACLA', 'Master Class', 'The Master Class for Computer Science students takes place biweekly and is mandatory for all students who are doing the Master''s Thesis Research Project. For students in the ‘Computer Science and Education’ or ‘Computer Science and Science Communication & Society’ specialisation, this is typically the second semester. For all other students, this is the second year. Note that as of 2024-2025, we separate the students into two groups according to their start semester, but keep the biweekly rhythm for the students. That is, the class is taught every week, but students are presumed to join only every second week. The Master Class aims at preparing students for finalising their Master’s programme, mainly focusing on two topics: (1) establishing your thesis and (2) career orientation.', 'https://studiegids.universiteitleiden.nl/en/courses/131634/master-class', '#001158', 'graduation', 0),
  ('4343BSMAC', 'Master Class Computer Science and Business Studies', 'The masterclass prepares students in their second year for their internship and writing their thesis. You will learn what is required in terms of research topics, host organisations, supervisors, project execution, thesis format, and more. You will gain an understanding of the evaluation criteria for master thesis research. You will learn about appropriate research methods in organisational contexts, such as interviews, surveys, text analysis and design science research. The masterclass is always offered in the fall semester and consists of 6 sessions. September starters follow the masterclass in their third semester; February starters in their second.', 'https://studiegids.universiteitleiden.nl/en/courses/132957/master-class-computer-science-and-business-studies', '#001158', 'graduation', 0),
  ('4343MRP22', 'Master''s Thesis Research Project (CS & BS)', 'The Master''s Thesis Research Project is an important part of the Master’s programme in Computer Science and Business Studies, and constitutes the final stage of the programme. Conducted in combination with a Business Research Internship, the thesis research project has as primary objective to allow students to acquire and demonstrate skills and knowledge to independently define, plan and execute a research project in an organisational context. Internship and thesis research should build on knowledge and skills acquired throughout the Computer Science and Business Studies programme and should have a clear focus on creating new knowledge, or extending existing knowledge through application in a new domain. As part of the research project, the student writes a scientific report, the Master’s thesis, and gives an oral presentation explaining the results of the research project, which is foll', 'https://studiegids.universiteitleiden.nl/en/courses/132956/masters-thesis-research-project-cs-bs', '#f46e32', 'graduation', 22),
  ('4343MRP30', 'Master''s Thesis Research Project (CS & SCS/EDU)', 'The Master''s Thesis Research Project is an important part of the Master’s programme in Computer Science, and constitutes the final stage of the programme. In the Master''s thesis project, the student is expected to conduct original research that contributes to a research field in computer science that the student studied during the programme. All aspects of scientific research, from reading relevant literature and formulating a research question up to reporting on and presenting the results will be addressed. As part of the research project, the student writes a scientific report, the Master’s thesis, and gives an oral presentation explaining the results of the research project, which is followed by a discussion known as the defence. Where', 'https://studiegids.universiteitleiden.nl/en/courses/131641/masters-thesis-research-project-cs-scsedu', '#a16207', 'graduation', 30),
  ('4343MRP42', 'Master''s Thesis Research Project (CS)', 'The Master''s Thesis Research Project is an important part of the Master’s programme in Computer Science, and constitutes the final stage of the programme. In the Master''s thesis project, the student is expected to conduct original research that contributes to a research field in computer science that the student studied during the programme. All aspects of scientific research, from reading relevant literature and formulating a research question up to reporting on and presenting the results will be addressed. As part of the research project, the student writes a scientific report, the Master’s thesis, and gives an oral presentation explaining the results of the research project, which is followed by a discussion known as the defence. Where', 'https://studiegids.universiteitleiden.nl/en/courses/131635/masters-thesis-research-project-cs', '#001158', 'graduation', 42),
  ('4343BSMDS', 'Model-Driven Systems Engineering', 'This course covers the concepts, principles, techniques and tools used in conceptual modelling of large-scale enterprise information systems as well as their implementation using model-driven engineering (MDE) appoaches. We cover the models and notations used in the requirements analysis and high-level design phases of the software development process using the Unified Modeling Language (UML). Students will also explore model implementation using a low code platform.', 'https://studiegids.universiteitleiden.nl/en/courses/131666/model-driven-systems-engineering', '#2563eb', 'chip', 6),
  ('4343MGAIX', 'Modern Game AI Algorithms', 'In the last years, Game AI has left the nerd interest area and is now known as incubator for many of the most important AI algorithms of our time. Almost the same methods are employed for beating the world champion in Go as well as solving very complex Chemistry problems for the first time in an automated fashion. We have recently witnessed programs beating human professionals in StarCraft and MOBA games and it is one part of the course to learn what kind of algorithms were used to do it. Providing AIs that play games well is one pillar of modern Game AI, the others are procedurally generating content (PCG) and modelling players, and of course all these 3 can be combined in various ways. Of course, these methods have ties also to other fields (e.g., behavior trees originated in robotics) and are not constrained to game uses. This renders the course a good introduction also to general AI.', 'https://studiegids.universiteitleiden.nl/en/courses/131628/modern-game-ai-algorithms', '#d946ef', 'book-open', 6),
  ('4343MOADX', 'Multicriteria Optimization and Decision Analysis', 'This course is about advanced computational optimization methods that can handle constraints and multiple objective functions, and as such deals with topics on the boundary of computer science and applied mathematics. Moreover, we discuss the principles of decision analysis with multiple conflicting criteria, where also some aspects of understanding human psychology (how we make choices) play a role. We will discuss the basic methodology and terminology of Operational Research, Nonlinear Mathematical Programming, and Decision Theory. We will emphasize the cutting edge research topics in the direction of multiobjective optimization and decision analysis (MODA). This emerging field of computational science has applications in various fields of technology, where balanced solutions are to be found in the presence of multiple conflicting objectives and constraints: These applications range ac', 'https://studiegids.universiteitleiden.nl/en/courses/131527/multicriteria-optimization-and-decision-analysis', '#06b6d4', 'book-open', 6),
  ('4343MMSY6', 'Multimedia Systems', 'This course is intended only (mandatory) for computer science students in the ACS - Advanced Computer Systems Specialization. Please do not register if you are not an ACS student. Multimedia systems is a wide and diverse area. In this course we focus on the scientific view of multimedia systems as presented in top major conferences (ACM or IEEE Multimedia) and journals and we provide advice, support and guidance for a final project that will be distributed (or placed online) to the public. The intention is to focus on current research trends (e.g. social computing, speech recognition, robotics) and gain insight into what is novel from a modern scientific perspective. From a practical standpoint, the technologies may be areas where the student will do further research, take in-depth courses in the specific area (i.e. Speech Understanding) or be used as components for future multimedia sys', 'https://studiegids.universiteitleiden.nl/en/courses/131600/multimedia-systems', '#f59e0b', 'chip', 6),
  ('4343MMEBX', 'Multimodal Models for Ecology and Biodiversity', 'This course introduces the fundamentals of multimodal models and their application in ecology for biodiversity monitoring. It focuses on leveraging heterogeneous data -such as images, audio, and biological measurements- to enhance the performance of automated monitoring systems. Key topics include the design, integration, and analysis of the components that constitute multimodal machine learning models. Biodiversity monitoring is essential for understanding species'' presence and ecosystem health. Traditional observation methods, while reliable, are time-consuming and prone to human bias. Advances in remote sensing, mobile technology, and machine learning have revolutionized data collection and analysis, enabling large-scale, multi-season monitoring. This course explores modern approaches to biodiversity assessment, focusing on the integration of diverse data modalities through machine le', 'https://studiegids.universiteitleiden.nl/en/courses/135828/multimodal-models-for-ecology-and-biodiversity', '#84cc16', 'dna', 6),
  ('4373MUMAB', 'Multiscale Mathematical Biology (BM)', 'Biological systems are so complex, that biologists often need to call in the help from mathematicians and computational scientists. These questions constitute a rich source of applied mathematical problems, for which often a range of mathematical and computational techniques need to be combined with one another. Mathematical insight into dynamical systems, pattern formation, complex networks, multiscale dynamics and parallel processing turn out to be a tremendous help while trying to ‘make sense of life’. This course will in particular introduce you to the mathematical modeling of healthy and diseased multicellular organisms, like plants and animals, including ourselves. A key question is how cells cooperate to create biological structure, and how this biological structure feeds back on gene expression. The focus will be on how to sharpen one’s intuition on the emergence of biological sy', 'https://studiegids.universiteitleiden.nl/en/courses/130756/multiscale-mathematical-biology-bm', '#22c55e', 'dna', 6),
  ('4032NLP6X', 'Natural Language Processing', 'Natural Language Processing (NLP) is a rapidly evolving field at the intersection of computer science, linguistics, and artificial intelligence. This undergraduate course provides an in-depth exploration of NLP techniques and methodologies. The course focusses on the fundamental concepts and tools of NLP, distinguishing between theoretical concepts and their implementation. On the theoretical side the students will learn about parts-of-speech, constituency and dependency parsing, distributional and compositional semantics. On the implementation side the course covers statistical and neural approaches to language modelling, sequence labelling and parsing, and selected applications. The course additionally discusses recurrent neural network architectures for NLP, as well as transformer models that form the basis for large language models, where encoder models like BERT and decoder models l', 'https://studiegids.universiteitleiden.nl/en/courses/131074/natural-language-processing', '#8b5cf6', 'book-open', 6),
  ('4343NLPSG', 'Natural Language Processing for Social Good', 'Natural Language Processing (NLP) is a branch of Artificial Intelligence (AI) that enables computers to interpret and generate human language. This field has become a cornerstone technology of the information age, as many of our social interactions are recorded as textual data—for example, social network posts, medical records, or customer evaluations. During the 2010s, deep learning techniques emerged and led to remarkable improvements in NLP tasks. A few years later, in the 2020s, the emergence of large language models (LLMs) like the ChatGPT core marked a major turning point in the field. This course examines the potential of NLP research to provide societal benefits. Students will learn and apply the latest NLP techniques to address societal issues including hate speech, sentiment and emotion analysis, misinformation, and social movements. Ethical considerations are integrated throug', 'https://studiegids.universiteitleiden.nl/en/courses/135833/natural-language-processing-for-social-good', '#a855f7', 'book-open', 6),
  ('4343PROFX', 'Proof Formalisation', 'A formal proof of a theorem starts from a given set of premises, and then applies logically sound rules to reach the desired conclusion. It is typically understood that such a proof could, in principle, be mechanically checked by a machine, to see if no extra assumptions were made, and each of the rules was applied correctly. Proofs encountered in the literature, on the other hand, are usually rendered in natural language. This increases the risk of human error — perhaps an induction hypothesis was applied incorrectly, the author forgot to cover a certain case, or some additional assumption was made inadvertently. Proof assistants help bridge this gap, by providing the user with a rigorous, machine-checked language to encode their assumptions, claims, and proofs. Modern proof assistants are general and flexible enough to express complicated arguments. They can also help to automate the "', 'https://studiegids.universiteitleiden.nl/en/courses/131629/proof-formalisation', '#3b82f6', 'book-open', 6),
  ('4343QUALG', 'Quantum Algorithms', 'Quantum computing is a relatively novel model of computation which has served as a hot buzz word in science writing for years. It is often singled out as one of the upcoming technologies which will revolutionize our world. Despite all the popularity and research efforts, the power quantum computing is still widely misunderstood and misrepresented. Moreover, very often it is claimed that for a genuine understanding of quantum computing one requires expertise in quantum physics; in this course you will see that this is not the case. In this course you will learn: what quantum computing is,', 'https://studiegids.universiteitleiden.nl/en/courses/131612/quantum-algorithms', '#6366f1', 'atom', 6),
  ('4343RECSX', 'Recommender Systems', 'AI-driven recommender systems have become integral to everyday decision-making, assisting users with choices from product purchases to movie selections and dining experiences. Powered by advanced AI algorithms and big data machine learning (ML), these systems analyze user behaviors, preferences, and product ratings to suggest personalized items or options. This course provides an in-depth introduction to recommender systems, a key component in various online services such as e-commerce, social media, and content streaming platforms. Students will explore the theoretical foundations and practical applications of recommender systems, learning about various algorithms, evaluation metrics, and current trends in the field. The course will combine theoretical lectures with hands-on assignments to develop practical skills in designing and implementing recommender systems.', 'https://studiegids.universiteitleiden.nl/en/courses/131630/recommender-systems', '#14b8a6', 'chart', 6),
  ('4343BSRGD', 'Regulatory Governance and Data Science', 'The need for more hereogenuous data and quality data for better AI outcomes is a non trivial issue. This is compounded by the need for control over digital data, which has become a critical societal and business concern. This course introduces students to the European and international public policies that affect data-ownership and control, data-science and AI. During the course, core concepts of regulatory governance in the EU will be introduced. The developments are looked at in a historic and comparative perspective. We consider how the European regulatory model differs from other models and how regulatory governance models relate to ethical and cultural notions. We will compare different digital governance models and look at their convergence and divergence. During the course, the students will engage with the topic of regulatory governance, by implementing a review that serves to de', 'https://studiegids.universiteitleiden.nl/en/courses/131675/regulatory-governance-and-data-science', '#001158', 'chart', 6),
  ('4343RINLX', 'Reinforcement Learning', 'Deep reinforcement learning is a field of Artificial Intelligence that has attracted much attention since impressive achievements in Robotics, and games such as StarCarft and Go, where human world champions were defeated by computer players. These results build on a combination of the rich history of reinforcement learning research and deep learning. This course teaches the field of deep reinforcement learning: How does it work, why does it work, and what are the reinforcement learning methods on which Robotics and AlphaGo’s success are based? By the end of the course you should have acquired a good understanding of the field of deep reinforcement learning. The defining characteristic of reinforcement learning is that agents learn through interaction with an environment, not unlike humans learn. Instead of telling a learner which action to take, the agent analyzes which action to take so', 'https://studiegids.universiteitleiden.nl/en/courses/131396/reinforcement-learning', '#4f46e5', 'brain', 6),
  ('4343ROBO6', 'Robotics', 'During the last decade we have seen an "explosion" of all kinds of robots designed for tasks that previously were deemed too challenging for machines. Robots have evolved from robotic arms and karts that could execute repetitive or simple tasks such as painting, welding and vacuum cleaning to autonomous cars, drones and humanoid helpers and servants that execute their tasks in much less controlled and even natural settings. For this modern robots require sophisticated adaptive capabilities. During the course we will have a thorough look at the important aspects of robot-architectures used in modern and state of the art robots. The use of various actuators and sensors will be studied. Algorithms for low level tasks such as movement, dead reckoning, obstacle-detection, and balancing will be presented. Intermediate level tasks such as mapping, obstacle recognition and avoidance, and more ad', 'https://studiegids.universiteitleiden.nl/en/courses/131631/robotics', '#d946ef', 'brain', 6),
  ('4343BSRPA', 'Role of IT in Public Administration', 'The course focuses on ICT challenges from a public governance perspective. This includes providing a basic understanding of the politico-administrative characteristics that distinguish public from private sector organizations and how these characteristics affect the challenges and opportunities of the use of ICT in government. Students will be introduced to Public Administration theories and the workings of government as well as different themes that are linked to the major problems identified for ICT projects within government. The themes include aspects of leadership in the public realm, regulatory and collaborative aspects, the governance of new technologies, and policy challenges in the big data age.', 'https://studiegids.universiteitleiden.nl/en/courses/131674/role-of-it-in-public-administration', '#001158', 'book-open', 6),
  ('4343SADRL', 'Seminar Advanced Deep Reinforcement Learning', 'For detailed information please visit the course website. Deep Reinforcement Learning (RL) is a field of artificial intelligence that has attracted much attention, for example being the first computer programme to beat the human world champion in the game of Go. In this seminar we will dive into recent deep reinforcement learning papers.', 'https://studiegids.universiteitleiden.nl/en/courses/131613/seminar-advanced-deep-reinforcement-learning', '#4f46e5', 'brain', 6),
  ('4343SADL6', 'Seminar Advances in Deep Learning', 'In recent years we have witnessed an explosion of research, development, and applications of Deep Learning. In this seminar we will dive into recent deep learning papers. The course is structured as follows. The course centers around a group assignment which runs from the very start of the course until the end. In groups you will first select a specific deep learning paper of interest from a top conference in deep learning or related fields, e.g. computer vision, NLP, audio processing, medical imaging. The main goal of the course is to understand the paper, replicate its results and extend/adapt it in some way. Throughout the course you present your progress to the group for feedback and give feedback to others. At the end of the course, you write a report about your results based on the guidlines of a true research paper.', 'https://studiegids.universiteitleiden.nl/en/courses/131397/seminar-advances-in-deep-learning', '#4f46e5', 'brain', 6),
  ('4343SMTAI', 'Seminar Trustworthy Artificial Intelligence', 'While in the past, performance has been the main focus of much work in artificial intelligence (AI), aspects of trustworthiness safety are increasingly recognised as similarly significant. This seminar course on trustworthy artificial intelligence aims to develop a deeper insight into various aspects of trustworthy AI. Students will work in groups of two on a range of topics from trustworthy artificial intelligence, which spans the robustness and verification of AI methods, including - but not restricted to - neural networks; the explainability and interpretability of the results obtained from AI algorithms; as well as bias and privacy issues in machine learning. Each group will be assigned recently published work from the research literature, which will serve as the starting point for an in-depth investigation of a specific topic; the results of this investigation will be presented in c', 'https://studiegids.universiteitleiden.nl/en/courses/131614/seminar-trustworthy-artificial-intelligence', '#7c3aed', 'brain', 6),
  ('4343SNACS', 'Social Network Analysis for Computer Scientists', 'This course deals with the computer science aspects of social network analysis, or more broadly, the field of network science. This field, with strong roots in computer science, aims to understand the real-world by analyzing interactions between the individuals in it. Examples of such networks include webgraphs, communication (telephone, email) and (scientific) collaboration networks, but perhaps most notably, (online) social networks, such as Facebook, Instagram and Twitter. With millions of nodes (users) and possibly billions of links (interacttion between users), traditional graph algorithms are often too complex and unable to solve trivial algorithmic and data mining related problems. Typical topics and research problems in this field include fundamental problems such as efficient retrieval, storage, anonymization and compression of graph data and computational problems such as compu', 'https://studiegids.universiteitleiden.nl/en/courses/123612/complex-networks-bm', '#2563eb', 'network', 6),
  ('4343BSSDP', 'Software Development and Product Management', 'ICT developments face increasing complexity. Technological challenges, combined with managerial and organisational issues, cause failure to a vast number of software development initiatives. The past decades, the earlier mentioned complexity has dominantly been managed by the application of project management methods and techniques. In recent years, the attention is shifting to product management philosophies/frameworks like Agile/Scrum. The lecture-based part of this course has been built on two pillars: 1. Software Product Management. How to manage software products during their complete life cycle, such that they generate the expected revenue and, as assets, represent the company''s sustainable value. This area includes topics, like: Product Strategy, Product planning and Strategic Management. 2. Software Product Development. How to manage the development of software products from idea', 'https://studiegids.universiteitleiden.nl/en/courses/131616/software-development-and-product-management', '#0ea5e9', 'code', 6),
  ('4343SWVRX', 'Software Verification', 'Digital systems have become so ubiquitous, that many of our daily activities depend on them. A glitch in the software or hardware of a digital system can cause us to miss an appointment or have to retype a text. But in the worst case, our lives can depend on the correctness of the system. Examples of such mission-critical systems are: traffic lights, automated breaking systems in cars, autonomous vehicles, autopilots, and guidence systems in rockets. Therefore, various methods have been developed for verifying the correctness of software and hardware. These methods go beyond mere testing by proving not only the presence but also the absence of bugs. This course mainly focuses on a software / hardware verification technique called model checking. Model Checking is a Turing-award winning approach for proving program correctness fully automatically. A model checker is a tool that takes anot', 'https://studiegids.universiteitleiden.nl/en/courses/131632/software-verification', '#ef4444', 'code', 6),
  ('4343SPDSX', 'Sports Data Science', 'The course aims to outline the (growing) role of data science in sports. Through various technological advances over the last years, it’s becoming easier to collect substantial datasets in sports, and practitioners are beginning to see the added benefit of collecting and analysing such data to achieve their goals. These goals might include optimizing one’s training efforts, personalising training schedules to the individual needs, understanding injury incidence and its prevention, optimizing the strategy in team sports and making data-driven tactical decisions. The course offers an introduction into the key concepts of sports science (including physiology and testing methods), an understanding of the basic questions to be answered in a range of sports disciplines, what types of data to expect or collect, and the specific data science techniques that are applied to these settings. The dat', 'https://studiegids.universiteitleiden.nl/en/courses/131633/sports-data-science', '#f59e0b', 'chart', 6),
  ('4433STATG', 'Statistical genetics', 'Statistical genetics plays an important role within the Life Sciences and impacts clinical research and decistion making, as well as food production and design. The course covers models for genetic data, including dependencies arising from family data (pedigrees) and genetic transmission across generations (recombinations, linkage, linkage disequilibrium, heritability). These models form the basis for methods used in animal and plant breeding as well in genetic association studies. Methods covered include genome wide linkage and association studies, the analysis of candidate genes, Mendelian randomization studies, and gene expression data.', 'https://studiegids.universiteitleiden.nl/en/courses/131639/statistical-genetics', '#84cc16', 'book-open', 6),
  ('4433STATL', 'Statistical Learning', 'Statistical learning refers to a vast set of tools for understanding data. These techniques are used in a wide range of industries and research fields. They have, for example, been used for: product and movie recommendations, predicting disease status, identifying fraudulent bank transactions, and identifying genes associated with specific diseases. This course provides a basis for understanding statistical learning techniques and teaches the skills to apply and evaluate them. The course will cover both supervised and unsupervised learning methods: Supervised statistical learning involves building a model for predicting an outcome (response, dependent) variable based on one or more input (predictor) variables. The supervised learning methods discussed will include classical and state-of-the-art classification methods: regularized regression (Ridge, Lasso), naive Bayes, linear and quadrat', 'https://studiegids.universiteitleiden.nl/en/courses/131648/statistical-learning', '#10b981', 'brain', 6),
  ('4343SYSSS', 'System and Software Security', 'Computer systems that communicate, process or store personal or company-critical data, need to be protected against attacks that undermine their security. These computer systems are used in diverse applications, ranging from low-energy sensor nodes in the Internet of Things, to high-performance servers in data centers. Therefore, security mechanisms need to adhere to the constraints imposed by the system with respect to energy consumption, performance, cost, etc. This course will concentrate on attacks and mitigations at the software and the hardware (processor) level, and will examine how these attacks and mitigations are constrained in real-world environments. The first part of the course will focus on vulnerabilities and their mitigations at the software level. We will overview the most important code vulnerability types and will study the state-of-the-art techniques for identifying s', 'https://studiegids.universiteitleiden.nl/en/courses/131601/system-and-software-security', '#e11d48', 'shield', 6),
  ('4343TXTMX', 'Text Mining', 'Text mining is one of the core application areas of Natural Language Processing (NLP). Key text mining tasks are text classification, information extraction, and sentiment analysis. NLP is a fast developing field that is grounded in fundamental models for text representation. It has attracted much attention from researchers in other fields and the general public, especially in recent times with the increasing power of large language models (LLMs). This course gives an overview of the field from both a theoretical angle (underlying models) and a practical angle (applications, challenges with data). In addition to the lectures, the students work on practical assignments. Outline:', 'https://studiegids.universiteitleiden.nl/en/courses/131617/text-mining', '#14b8a6', 'chart', 6),
  ('4343URBC6', 'Urban computing', 'Urban computing, as an interdisciplinary field, is the science of using computing technology in solving urban and environmental challenges such as traffic, and pollution. This course provides a comprehensive introduction to this topic. Throughout the course, students will get familiar with data acquisitions, integration, and modeling skills required for urban computing research. Spatio-temporal data is the data collected as a result of movement of mobile objects, such as cars and people, over space. Spatio-temporal data mining is the core to most urban computing research projects. Most previously designed machine learning algorithms do not consider the specific characteristics of spatio-temporal data. In this course, we will talk about how different classes of machine learning algorithms have been designed so far to perform on such data. We will also learn how additional data sources can', 'https://studiegids.universiteitleiden.nl/en/courses/131618/urban-computing', '#0ea5e9', 'book-open', 6),
  ('4383VGFR6', 'Video Games for Research', 'Scientific experiments increasingly involve interactive elements and virtual environments that make use of the technological advancements in video game development. Some studies even specifically involve video games to collect data or to use them to educate people on a specific issue. However, designing and conducting game-based research projects requires understanding not just of one''s own field of research, but also of the conventions and practical considerations that are part of video game development. In this course, you will learn how to design and conduct a game-based research project that involves either the modification of an existing video game, or the purposeful development of a new interactive experience. In the process, you will learn about existing ''serious game'' projects, recent developments in game research more generally, and technological affordances that can be used in ', 'https://studiegids.universiteitleiden.nl/en/courses/131619/video-games-for-research', '#d946ef', 'graduation', 6)
on conflict (code) do update
set title = excluded.title,
    description = excluded.description,
    studiegids_url = excluded.studiegids_url,
    color = excluded.color,
    icon = excluded.icon,
    ec = excluded.ec;

with mapping (course_code, spec_code, role) as (values
  ('4343ADVDX', 'acs', 'elective'),
  ('4343ADVDX', 'ai', 'elective'),
  ('4343ADVDX', 'bioinf', 'core'),
  ('4343ADVDX', 'csbs', 'elective'),
  ('4343ADVDX', 'cse', 'elective'),
  ('4343ADVDX', 'ds', 'core'),
  ('4343ADVDX', 'foc', 'elective'),
  ('4343ADVDX', 'scss', 'elective'),
  ('4343AIART', 'acs', 'elective'),
  ('4343AIART', 'ai', 'elective'),
  ('4343AIART', 'csbs', 'elective'),
  ('4343AIART', 'cse', 'elective'),
  ('4343AIART', 'ds', 'elective'),
  ('4343AIART', 'foc', 'elective'),
  ('4343AIART', 'scss', 'elective'),
  ('4343AISOC', 'ai', 'core'),
  ('4343APQALY', 'acs', 'elective'),
  ('4343APQALY', 'ai', 'elective'),
  ('4343APQALY', 'csbs', 'elective'),
  ('4343APQALY', 'cse', 'elective'),
  ('4343APQALY', 'ds', 'elective'),
  ('4343APQALY', 'foc', 'elective'),
  ('4343APQALY', 'scss', 'elective'),
  ('4383ARCR3', 'ai', 'elective'),
  ('4343AUDIO', 'acs', 'elective'),
  ('4343AUDIO', 'ai', 'elective'),
  ('4343AUDIO', 'csbs', 'elective'),
  ('4343AUDIO', 'cse', 'elective'),
  ('4343AUDIO', 'ds', 'elective'),
  ('4343AUDIO', 'foc', 'elective'),
  ('4343AUDIO', 'scss', 'elective'),
  ('4343AUTMX', 'acs', 'elective'),
  ('4343AUTMX', 'ai', 'core'),
  ('4343AUTMX', 'bioinf', 'elective'),
  ('4343AUTMX', 'csbs', 'elective'),
  ('4343AUTMX', 'cse', 'elective'),
  ('4343AUTMX', 'ds', 'elective'),
  ('4343AUTMX', 'foc', 'elective'),
  ('4343AUTMX', 'scss', 'elective'),
  ('4343BAYOP', 'acs', 'elective'),
  ('4343BAYOP', 'ai', 'elective'),
  ('4343BAYOP', 'bioinf', 'elective'),
  ('4343BAYOP', 'csbs', 'elective'),
  ('4343BAYOP', 'cse', 'elective'),
  ('4343BAYOP', 'ds', 'elective'),
  ('4343BAYOP', 'foc', 'elective'),
  ('4343BAYOP', 'scss', 'elective'),
  ('4343BIOMD', 'acs', 'elective'),
  ('4343BIOMD', 'ai', 'elective'),
  ('4343BIOMD', 'bioinf', 'core'),
  ('4343BIOMD', 'csbs', 'elective'),
  ('4343BIOMD', 'cse', 'elective'),
  ('4343BIOMD', 'ds', 'elective'),
  ('4343BIOMD', 'foc', 'elective'),
  ('4343BIOMD', 'scss', 'elective'),
  ('4343BICAI', 'acs', 'elective'),
  ('4343BICAI', 'ai', 'elective'),
  ('4343BICAI', 'bioinf', 'elective'),
  ('4343BICAI', 'csbs', 'elective'),
  ('4343BICAI', 'cse', 'elective'),
  ('4343BICAI', 'ds', 'elective'),
  ('4343BICAI', 'foc', 'elective'),
  ('4343BICAI', 'scss', 'elective'),
  ('4343BSCC4', 'csbs', 'core'),
  ('4343CICSX', 'acs', 'elective'),
  ('4343CICSX', 'ai', 'elective'),
  ('4343CICSX', 'csbs', 'elective'),
  ('4343CICSX', 'cse', 'elective'),
  ('4343CICSX', 'ds', 'elective'),
  ('4343CICSX', 'foc', 'elective'),
  ('4343CICSX', 'scss', 'elective'),
  ('4343CLCMX', 'acs', 'core'),
  ('4343CLCMX', 'ai', 'elective'),
  ('4343CLCMX', 'bioinf', 'elective'),
  ('4343CLCMX', 'cse', 'elective'),
  ('4343CLCMX', 'ds', 'elective'),
  ('4343CLCMX', 'foc', 'elective'),
  ('4343CLCMX', 'scss', 'elective'),
  ('4609COMNWY', 'acs', 'elective'),
  ('4609COMNWY', 'ai', 'elective'),
  ('4609COMNWY', 'bioinf', 'elective'),
  ('4609COMNWY', 'csbs', 'elective'),
  ('4609COMNWY', 'cse', 'elective'),
  ('4609COMNWY', 'ds', 'elective'),
  ('4609COMNWY', 'foc', 'elective'),
  ('4609COMNWY', 'scss', 'elective'),
  ('4383COMCR', 'acs', 'elective'),
  ('4383COMCR', 'ai', 'core'),
  ('4383COMCR', 'csbs', 'elective'),
  ('4383COMCR', 'cse', 'elective'),
  ('4383COMCR', 'ds', 'elective'),
  ('4383COMCR', 'foc', 'elective'),
  ('4383COMCR', 'scss', 'elective'),
  ('4343CIMTO', 'acs', 'elective'),
  ('4343CIMTO', 'ai', 'elective'),
  ('4343CIMTO', 'bioinf', 'elective'),
  ('4343CIMTO', 'csbs', 'elective'),
  ('4343CIMTO', 'cse', 'elective'),
  ('4343CIMTO', 'ds', 'elective'),
  ('4343CIMTO', 'foc', 'elective'),
  ('4343CIMTO', 'scss', 'elective'),
  ('4343CMS6X', 'acs', 'elective'),
  ('4343CMS6X', 'ai', 'elective'),
  ('4343CMS6X', 'csbs', 'elective'),
  ('4343CMS6X', 'cse', 'elective'),
  ('4343CMS6X', 'ds', 'elective'),
  ('4343CMS6X', 'foc', 'core'),
  ('4343CMS6X', 'scss', 'elective'),
  ('4433COMST', 'ds', 'elective'),
  ('4343CRYPE', 'acs', 'elective'),
  ('4343CRYPE', 'ai', 'elective'),
  ('4343CRYPE', 'csbs', 'elective'),
  ('4343CRYPE', 'cse', 'elective'),
  ('4343CRYPE', 'ds', 'elective'),
  ('4343CRYPE', 'foc', 'elective'),
  ('4343CRYPE', 'scss', 'elective'),
  ('4343BSCSM', 'csbs', 'elective'),
  ('4343DASPR', 'csbs', 'elective'),
  ('4343DASPR', 'ds', 'elective'),
  ('4433DATVI', 'ds', 'elective'),
  ('4343DDORW', 'acs', 'elective'),
  ('4343DDORW', 'ai', 'elective'),
  ('4343DDORW', 'csbs', 'elective'),
  ('4343DDORW', 'cse', 'elective'),
  ('4343DDORW', 'ds', 'elective'),
  ('4343DDORW', 'foc', 'elective'),
  ('4343DDORW', 'scss', 'elective'),
  ('4343BSDPM', 'acs', 'elective'),
  ('4343BSDPM', 'ai', 'elective'),
  ('4343BSDPM', 'csbs', 'elective'),
  ('4343BSDPM', 'cse', 'elective'),
  ('4343BSDPM', 'ds', 'elective'),
  ('4343BSDPM', 'foc', 'elective'),
  ('4343BSDPM', 'scss', 'elective'),
  ('4343DISYX', 'acs', 'core'),
  ('4343DISYX', 'ai', 'elective'),
  ('4343DISYX', 'csbs', 'elective'),
  ('4343DISYX', 'cse', 'elective'),
  ('4343DISYX', 'ds', 'elective'),
  ('4343DISYX', 'foc', 'elective'),
  ('4343DISYX', 'scss', 'elective'),
  ('4343EMBSS', 'acs', 'core'),
  ('4343EMBSS', 'ai', 'elective'),
  ('4343EMBSS', 'csbs', 'elective'),
  ('4343EMBSS', 'cse', 'elective'),
  ('4343EMBSS', 'ds', 'elective'),
  ('4343EMBSS', 'foc', 'elective'),
  ('4343EMBSS', 'scss', 'elective'),
  ('4343BSEA6', 'csbs', 'core'),
  ('4343EVALX', 'acs', 'elective'),
  ('4343EVALX', 'ai', 'core'),
  ('4343EVALX', 'bioinf', 'core'),
  ('4343EVALX', 'csbs', 'elective'),
  ('4343EVALX', 'cse', 'elective'),
  ('4343EVALX', 'ds', 'elective'),
  ('4343EVALX', 'foc', 'elective'),
  ('4343EVALX', 'scss', 'elective'),
  ('4433EXPDA', 'ds', 'elective'),
  ('4343FSWT6', 'acs', 'elective'),
  ('4343FSWT6', 'ai', 'elective'),
  ('4343FSWT6', 'csbs', 'elective'),
  ('4343FSWT6', 'cse', 'elective'),
  ('4343FSWT6', 'ds', 'elective'),
  ('4343FSWT6', 'foc', 'core'),
  ('4343FSWT6', 'scss', 'elective'),
  ('4383HICNM', 'ai', 'elective'),
  ('4343BSGBG', 'csbs', 'core'),
  ('4343HIPX6', 'acs', 'core'),
  ('4343HIPX6', 'ai', 'elective'),
  ('4343HIPX6', 'csbs', 'elective'),
  ('4343HIPX6', 'cse', 'elective'),
  ('4343HIPX6', 'ds', 'elective'),
  ('4343HIPX6', 'foc', 'elective'),
  ('4343HIPX6', 'scss', 'elective'),
  ('4433HDDAN', 'bioinf', 'elective'),
  ('4343BSICT', 'csbs', 'elective'),
  ('4343MMAV6', 'acs', 'elective'),
  ('4343MMAV6', 'ai', 'elective'),
  ('4343MMAV6', 'bioinf', 'core'),
  ('4343MMAV6', 'csbs', 'elective'),
  ('4343MMAV6', 'cse', 'elective'),
  ('4343MMAV6', 'ds', 'elective'),
  ('4343MMAV6', 'foc', 'elective'),
  ('4343MMAV6', 'scss', 'elective'),
  ('4343INFRX', 'acs', 'elective'),
  ('4343INFRX', 'ai', 'elective'),
  ('4343INFRX', 'csbs', 'elective'),
  ('4343INFRX', 'cse', 'elective'),
  ('4343INFRX', 'ds', 'core'),
  ('4343INFRX', 'foc', 'elective'),
  ('4343INFRX', 'scss', 'elective'),
  ('4343ITDM6', 'acs', 'elective'),
  ('4343ITDM6', 'ai', 'elective'),
  ('4343ITDM6', 'csbs', 'elective'),
  ('4343ITDM6', 'cse', 'elective'),
  ('4343ITDM6', 'ds', 'elective'),
  ('4343ITDM6', 'foc', 'elective'),
  ('4343ITDM6', 'scss', 'elective'),
  ('4343INDLX', 'acs', 'elective'),
  ('4343INDLX', 'ai', 'core'),
  ('4343INDLX', 'bioinf', 'core'),
  ('4343INDLX', 'csbs', 'elective'),
  ('4343INDLX', 'cse', 'elective'),
  ('4343INDLX', 'ds', 'core'),
  ('4343INDLX', 'foc', 'elective'),
  ('4343INDLX', 'scss', 'elective'),
  ('4343IRPRJ', 'bioinf', 'elective'),
  ('4433LGMO6', 'ds', 'elective'),
  ('4343BSMLB', 'csbs', 'elective'),
  ('4343BSMSE', 'csbs', 'elective'),
  ('4343MACLA', 'acs', 'elective'),
  ('4343MACLA', 'ai', 'elective'),
  ('4343MACLA', 'bioinf', 'elective'),
  ('4343MACLA', 'cse', 'elective'),
  ('4343MACLA', 'ds', 'elective'),
  ('4343MACLA', 'foc', 'elective'),
  ('4343MACLA', 'scss', 'elective'),
  ('4343BSMAC', 'csbs', 'elective'),
  ('4343MRP22', 'csbs', 'elective'),
  ('4343MRP30', 'cse', 'elective'),
  ('4343MRP30', 'scss', 'elective'),
  ('4343MRP42', 'acs', 'elective'),
  ('4343MRP42', 'ai', 'elective'),
  ('4343MRP42', 'bioinf', 'elective'),
  ('4343MRP42', 'ds', 'elective'),
  ('4343MRP42', 'foc', 'elective'),
  ('4343BSMDS', 'csbs', 'core'),
  ('4343MGAIX', 'acs', 'elective'),
  ('4343MGAIX', 'ai', 'core'),
  ('4343MGAIX', 'csbs', 'elective'),
  ('4343MGAIX', 'cse', 'elective'),
  ('4343MGAIX', 'ds', 'elective'),
  ('4343MGAIX', 'foc', 'core'),
  ('4343MGAIX', 'scss', 'elective'),
  ('4343MOADX', 'acs', 'elective'),
  ('4343MOADX', 'ai', 'core'),
  ('4343MOADX', 'bioinf', 'elective'),
  ('4343MOADX', 'csbs', 'elective'),
  ('4343MOADX', 'cse', 'elective'),
  ('4343MOADX', 'ds', 'elective'),
  ('4343MOADX', 'foc', 'elective'),
  ('4343MOADX', 'scss', 'elective'),
  ('4343MMSY6', 'acs', 'core'),
  ('4343MMSY6', 'ai', 'elective'),
  ('4343MMSY6', 'csbs', 'elective'),
  ('4343MMSY6', 'cse', 'elective'),
  ('4343MMSY6', 'ds', 'elective'),
  ('4343MMSY6', 'foc', 'elective'),
  ('4343MMSY6', 'scss', 'elective'),
  ('4343MMEBX', 'acs', 'elective'),
  ('4343MMEBX', 'ai', 'elective'),
  ('4343MMEBX', 'bioinf', 'core'),
  ('4343MMEBX', 'csbs', 'elective'),
  ('4343MMEBX', 'cse', 'elective'),
  ('4343MMEBX', 'ds', 'elective'),
  ('4343MMEBX', 'foc', 'elective'),
  ('4343MMEBX', 'scss', 'elective'),
  ('4373MUMAB', 'bioinf', 'elective'),
  ('4032NLP6X', 'csbs', 'elective'),
  ('4343NLPSG', 'acs', 'elective'),
  ('4343NLPSG', 'ai', 'elective'),
  ('4343NLPSG', 'cse', 'elective'),
  ('4343NLPSG', 'ds', 'elective'),
  ('4343NLPSG', 'foc', 'elective'),
  ('4343NLPSG', 'scss', 'elective'),
  ('4343PROFX', 'acs', 'elective'),
  ('4343PROFX', 'ai', 'elective'),
  ('4343PROFX', 'csbs', 'elective'),
  ('4343PROFX', 'cse', 'elective'),
  ('4343PROFX', 'ds', 'elective'),
  ('4343PROFX', 'foc', 'core'),
  ('4343PROFX', 'scss', 'elective'),
  ('4343QUALG', 'acs', 'elective'),
  ('4343QUALG', 'ai', 'elective'),
  ('4343QUALG', 'bioinf', 'elective'),
  ('4343QUALG', 'csbs', 'elective'),
  ('4343QUALG', 'cse', 'elective'),
  ('4343QUALG', 'ds', 'elective'),
  ('4343QUALG', 'foc', 'core'),
  ('4343QUALG', 'scss', 'elective'),
  ('4343RECSX', 'acs', 'elective'),
  ('4343RECSX', 'ai', 'elective'),
  ('4343RECSX', 'csbs', 'elective'),
  ('4343RECSX', 'cse', 'elective'),
  ('4343RECSX', 'ds', 'elective'),
  ('4343RECSX', 'foc', 'elective'),
  ('4343RECSX', 'scss', 'elective'),
  ('4343BSRGD', 'csbs', 'elective'),
  ('4343BSRGD', 'ds', 'elective'),
  ('4343RINLX', 'acs', 'elective'),
  ('4343RINLX', 'ai', 'core'),
  ('4343RINLX', 'bioinf', 'elective'),
  ('4343RINLX', 'csbs', 'elective'),
  ('4343RINLX', 'cse', 'elective'),
  ('4343RINLX', 'ds', 'core'),
  ('4343RINLX', 'foc', 'elective'),
  ('4343RINLX', 'scss', 'elective'),
  ('4343ROBO6', 'acs', 'elective'),
  ('4343ROBO6', 'ai', 'elective'),
  ('4343ROBO6', 'csbs', 'elective'),
  ('4343ROBO6', 'cse', 'elective'),
  ('4343ROBO6', 'ds', 'elective'),
  ('4343ROBO6', 'foc', 'elective'),
  ('4343ROBO6', 'scss', 'elective'),
  ('4343BSRPA', 'csbs', 'elective'),
  ('4343SADRL', 'acs', 'elective'),
  ('4343SADRL', 'ai', 'elective'),
  ('4343SADRL', 'bioinf', 'elective'),
  ('4343SADRL', 'csbs', 'elective'),
  ('4343SADRL', 'cse', 'elective'),
  ('4343SADRL', 'ds', 'elective'),
  ('4343SADRL', 'foc', 'elective'),
  ('4343SADRL', 'scss', 'elective'),
  ('4343SADL6', 'acs', 'elective'),
  ('4343SADL6', 'ai', 'elective'),
  ('4343SADL6', 'bioinf', 'elective'),
  ('4343SADL6', 'csbs', 'elective'),
  ('4343SADL6', 'cse', 'elective'),
  ('4343SADL6', 'ds', 'elective'),
  ('4343SADL6', 'foc', 'elective'),
  ('4343SADL6', 'scss', 'elective'),
  ('4343SMTAI', 'acs', 'elective'),
  ('4343SMTAI', 'ai', 'elective'),
  ('4343SMTAI', 'bioinf', 'elective'),
  ('4343SMTAI', 'csbs', 'elective'),
  ('4343SMTAI', 'cse', 'elective'),
  ('4343SMTAI', 'ds', 'elective'),
  ('4343SMTAI', 'foc', 'elective'),
  ('4343SMTAI', 'scss', 'elective'),
  ('4343SNACS', 'acs', 'elective'),
  ('4343SNACS', 'ai', 'elective'),
  ('4343SNACS', 'bioinf', 'elective'),
  ('4343SNACS', 'csbs', 'elective'),
  ('4343SNACS', 'cse', 'elective'),
  ('4343SNACS', 'ds', 'core'),
  ('4343SNACS', 'foc', 'elective'),
  ('4343SNACS', 'scss', 'elective'),
  ('4343BSSDP', 'acs', 'elective'),
  ('4343BSSDP', 'ai', 'elective'),
  ('4343BSSDP', 'csbs', 'core'),
  ('4343BSSDP', 'cse', 'elective'),
  ('4343BSSDP', 'ds', 'elective'),
  ('4343BSSDP', 'foc', 'elective'),
  ('4343BSSDP', 'scss', 'elective'),
  ('4343SWVRX', 'acs', 'elective'),
  ('4343SWVRX', 'ai', 'elective'),
  ('4343SWVRX', 'csbs', 'elective'),
  ('4343SWVRX', 'cse', 'elective'),
  ('4343SWVRX', 'ds', 'elective'),
  ('4343SWVRX', 'foc', 'core'),
  ('4343SWVRX', 'scss', 'elective'),
  ('4343SPDSX', 'acs', 'elective'),
  ('4343SPDSX', 'ai', 'elective'),
  ('4343SPDSX', 'csbs', 'elective'),
  ('4343SPDSX', 'cse', 'elective'),
  ('4343SPDSX', 'ds', 'elective'),
  ('4343SPDSX', 'foc', 'elective'),
  ('4343SPDSX', 'scss', 'elective'),
  ('4433STATG', 'bioinf', 'elective'),
  ('4433STATL', 'ds', 'elective'),
  ('4343SYSSS', 'acs', 'core'),
  ('4343SYSSS', 'ai', 'elective'),
  ('4343SYSSS', 'csbs', 'elective'),
  ('4343SYSSS', 'cse', 'elective'),
  ('4343SYSSS', 'ds', 'elective'),
  ('4343SYSSS', 'foc', 'elective'),
  ('4343SYSSS', 'scss', 'elective'),
  ('4343TXTMX', 'acs', 'elective'),
  ('4343TXTMX', 'ai', 'elective'),
  ('4343TXTMX', 'bioinf', 'elective'),
  ('4343TXTMX', 'csbs', 'elective'),
  ('4343TXTMX', 'cse', 'elective'),
  ('4343TXTMX', 'ds', 'core'),
  ('4343TXTMX', 'foc', 'elective'),
  ('4343TXTMX', 'scss', 'elective'),
  ('4343URBC6', 'acs', 'elective'),
  ('4343URBC6', 'ai', 'elective'),
  ('4343URBC6', 'csbs', 'elective'),
  ('4343URBC6', 'cse', 'elective'),
  ('4343URBC6', 'ds', 'elective'),
  ('4343URBC6', 'foc', 'elective'),
  ('4343URBC6', 'scss', 'elective'),
  ('4383VGFR6', 'acs', 'elective'),
  ('4383VGFR6', 'ai', 'elective'),
  ('4383VGFR6', 'csbs', 'elective'),
  ('4383VGFR6', 'cse', 'elective'),
  ('4383VGFR6', 'ds', 'elective'),
  ('4383VGFR6', 'foc', 'elective'),
  ('4383VGFR6', 'scss', 'elective')
)
insert into public.course_specializations (course_id, specialization_id, role)
select c.id, s.id, m.role
from mapping m
join public.courses c on c.code = m.course_code
join public.specializations s on s.code = m.spec_code
on conflict (course_id, specialization_id) do update
set role = excluded.role;

insert into public.admins (email) values
  ('s.r.de.groot.2@umail.leidenuniv.nl')
on conflict (email) do nothing;
