-- Seed data for LeidenCS.
-- Generated from the Leiden University study guide 2025-2026.
-- Run `python3 scripts/scrape_studiegids.py --refresh` to update from source pages.

insert into public.specializations (code, name, study_id) values
  ('acs', 'Advanced Computing and Systems', '10550'),
  ('ai', 'Artificial Intelligence', '10551'),
  ('bioinf', 'Bioinformatics', '10552'),
  ('cse', 'Computer Science and Education', '10553'),
  ('scss', 'Computer Science and Science Communication and Society', '10554'),
  ('ds', 'Data Science', '10555'),
  ('foc', 'Foundations of Computing', '10556'),
  ('csbs', 'Computer Science and Business Studies', '10602')
on conflict (code) do update
set name = excluded.name,
    study_id = excluded.study_id;

insert into public.courses (code, title, description, studiegids_url, color, icon, ec, offered_semesters) values
  ('4343ADVDX', 'Advances in Data Mining', 'Students learn modern data mining methods for massive datasets, including streaming data, similarity search, anomaly detection, clustering, recommender systems and dimensionality reduction.', 'https://studiegids.universiteitleiden.nl/en/courses/131394/advances-in-data-mining', '#06b6d4', 'chart', 6, array['S1']::text[]),
  ('4343AIART', 'AI and Art', 'This course combines generative AI techniques with critical reflection on creativity, authorship, aesthetics, ethics and the changing role of machines in artistic practice.', 'https://studiegids.universiteitleiden.nl/en/courses/135824/ai-and-art', '#ec4899', 'book-open', 6, array['S1']::text[]),
  ('4343AISOC', 'AI in Society', 'Students examine AI through social, political, ethical and environmental lenses, then apply these perspectives to real domains through a speculative hands-on project.', 'https://studiegids.universiteitleiden.nl/en/courses/131636/ai-in-society', '#8b5cf6', 'book-open', 6, array['S2']::text[]),
  ('4343APQALY', 'Applied Quantum Algorithms', 'An advanced quantum computing course focused on practical algorithm design for chemistry, physics, machine learning and the error correction methods needed for noisy devices.', 'https://studiegids.universiteitleiden.nl/en/courses/131620/applied-quantum-algorithms', '#6366f1', 'atom', 6, array['S2']::text[]),
  ('4383ARCR3', 'Artificial Creatures', 'Students explore emotional, creative, curious and lifelike robots, then build an artificial creature that makes a chosen human-like quality tangible.', 'https://studiegids.universiteitleiden.nl/en/courses/131637/artificial-creatures', '#d946ef', 'book-open', 3, array['S1']::text[]),
  ('4343AUDIO', 'Audio Processing and Indexing', 'This seminar covers speech recognition, audio synthesis and content-based audio retrieval through lectures, workshops, literature study, student presentations and final project demos.', 'https://studiegids.universiteitleiden.nl/en/courses/131607/audio-processing-and-indexing', '#3b82f6', 'book-open', 6, array['S1']::text[]),
  ('4343AUTMX', 'Automated Machine Learning', 'Students study how AutoML selects algorithms and tunes hyperparameters so machine learning systems can achieve strong predictive performance on new datasets.', 'https://studiegids.universiteitleiden.nl/en/courses/131608/automated-machine-learning', '#8b5cf6', 'brain', 6, array['S1']::text[]),
  ('4343BAYOP', 'Bayesian Optimization', 'This course teaches Bayesian optimization for expensive black-box functions, covering Gaussian processes, acquisition functions, noisy observations, constraints and practical Python applications.', 'https://studiegids.universiteitleiden.nl/en/courses/131609/bayesian-optimization', '#10b981', 'book-open', 6, array['S1']::text[]),
  ('4343BIOMD', 'Bio-Modeling', 'Students model biological processes with formal computational frameworks such as Boolean networks and Petri nets, combining lectures, tool practice and interdisciplinary project work.', 'https://studiegids.universiteitleiden.nl/en/courses/131525/bio-modeling', '#84cc16', 'dna', 6, array['S2']::text[]),
  ('4343BICAI', 'Brain-inspired Computing for AI', 'Students investigate efficient AI inspired by the brain, including compression, quantization, neuromorphic computing and hardware approaches for low-power machine learning.', 'https://studiegids.universiteitleiden.nl/en/courses/135825/brain-inspired-computing-for-ai', '#7c3aed', 'book-open', 6, array['S1']::text[]),
  ('4343BSCC4', 'Capstone Cases', 'Second-year students apply earlier business and IT knowledge to real or realistic company cases, analyzing problems and presenting practical recommendations to management.', 'https://studiegids.universiteitleiden.nl/en/courses/131668/capstone-cases', '#001158', 'book-open', 4, array['S1', 'S2']::text[]),
  ('4343CICSX', 'Causal Inference for Computer Scientists', 'Students learn causal inference for machine learning, using structural causal models, potential outcomes, interventions, counterfactuals and data-driven causal discovery methods.', 'https://studiegids.universiteitleiden.nl/en/courses/131621/causal-inference-for-computer-scientists', '#14b8a6', 'book-open', 6, array['S2']::text[]),
  ('4343CLCMX', 'Cloud Computing', 'This course surveys cloud computing from infrastructure and deployment models to scalability, resource management, cloud programming, research papers and hands-on platform assignments.', 'https://studiegids.universiteitleiden.nl/en/courses/131602/cloud-computing', '#0ea5e9', 'cloud', 6, array['S2']::text[]),
  ('4609COMNWY', 'Complex Networks (BM)', 'Students study complex networks across physics, mathematics and computer science, covering real-world network properties, models, algorithms, visualization, epidemics and computational complexity.', 'https://studiegids.universiteitleiden.nl/en/courses/131371/complex-networks-bm', '#2563eb', 'network', 6, array['S1']::text[]),
  ('4383COMCR', 'Computational Creativity', 'Students explore computational models of creativity, creative agents, co-creative systems, evaluation methods and philosophical questions through literature discussions and a practical project.', 'https://studiegids.universiteitleiden.nl/en/courses/131610/computational-creativity', '#f43f5e', 'book-open', 6, array['S1']::text[]),
  ('4343CIMTO', 'Computational Imaging and Tomography', 'This seminar introduces computational imaging and tomography, connecting physical measurement models, inverse problems, algorithms, high-performance computing and advanced research literature.', 'https://studiegids.universiteitleiden.nl/en/courses/131622/computational-imaging-and-tomography', '#0ea5e9', 'book-open', 6, array['S2']::text[]),
  ('4343CMS6X', 'Computational Models and Semantics', 'Students study computational models and programming language semantics, using functional, probabilistic and categorical perspectives alongside Haskell assignments and a research project.', 'https://studiegids.universiteitleiden.nl/en/courses/131611/computational-models-and-semantics', '#3b82f6', 'book-open', 6, array['S1', 'S2']::text[]),
  ('4433COMST', 'Computational Statistics', 'This course introduces computational statistics through numerical methods, algorithms, simulation and mathematical techniques for solving statistical problems in practice.', 'https://studiegids.universiteitleiden.nl/en/courses/131643/computational-statistics', '#06b6d4', 'chart', 3, array['S2']::text[]),
  ('4343CRYPE', 'Cryptographic Engineering', 'Students study secure implementation of cryptographic algorithms in hardware and software, considering design constraints such as performance, resources, energy use and side-channel risks.', 'https://studiegids.universiteitleiden.nl/en/courses/131603/cryptographic-engineering', '#e11d48', 'shield', 6, array['S2']::text[]),
  ('4343BSCSM', 'Cyber Security Management', 'A management-oriented cybersecurity course for future CIOs, covering organizational risk, governance, policy and the business impact of ICT security decisions.', 'https://studiegids.universiteitleiden.nl/en/courses/131665/cyber-security-management', '#9f1239', 'shield', 3, array['S1']::text[]),
  ('4343DASPR', 'Data Science in Practice', 'Students work on real Fieldlab data problems, moving from problem exploration and data quality assessment to solution design and applied data science practice.', 'https://studiegids.universiteitleiden.nl/en/courses/131644/data-science-in-practice', '#059669', 'chart', 6, array['S1']::text[]),
  ('4433DATVI', 'Data Visualization', 'Students learn how to design effective statistical visualizations, evaluate graphical choices and communicate data patterns clearly across applied research contexts.', 'https://studiegids.universiteitleiden.nl/en/courses/131645/data-visualization', '#f59e0b', 'chart', 6, array['S2']::text[]),
  ('4343DDORW', 'Data-driven optimisation for Real-World Applications', 'Students model and solve real-world optimization problems with constraints, uncertainty and data, connecting theoretical foundations to practical decision-making applications.', 'https://studiegids.universiteitleiden.nl/en/courses/135826/data-driven-optimisation-for-real-world-applications', '#10b981', 'chart', 6, array['S2']::text[]),
  ('4343BSDPM', 'Data-driven Policy Making', 'Students examine how governments use data for policy, focusing on digital-era governance, data readiness, infrastructure, accountability and technology-driven public innovation.', 'https://studiegids.universiteitleiden.nl/en/courses/131673/data-driven-policy-making', '#001158', 'chart', 6, array['S1']::text[]),
  ('4343DISYX', 'Distributed Systems', 'This course covers the principles behind distributed systems that power social networks, government services and streaming platforms, with attention to reliability and coordination.', 'https://studiegids.universiteitleiden.nl/en/courses/131623/distributed-systems', '#f97316', 'cloud', 6, array['S2']::text[]),
  ('4343EMBSS', 'Embedded Systems and Software', 'Students study embedded systems that interact tightly with physical environments, from appliances and medical devices to portable systems, with focus on architecture and software constraints.', 'https://studiegids.universiteitleiden.nl/en/courses/131604/embedded-systems-and-software', '#ea580c', 'code', 6, array['S2']::text[]),
  ('4343BSEA6', 'Enterprise Architecture', 'Students learn enterprise architecture methods and models for designing coherent organizations, aligning business processes, information systems, principles and implementation choices.', 'https://studiegids.universiteitleiden.nl/en/courses/131667/enterprise-architecture', '#64748b', 'book-open', 6, array['S2']::text[]),
  ('4343EVALX', 'Evolutionary Algorithms', 'Students study evolutionary algorithms that search for solutions through population-based variation and selection, applying evolutionary computation to complex optimization problems.', 'https://studiegids.universiteitleiden.nl/en/courses/131526/evolutionary-algorithms', '#8b5cf6', 'book-open', 6, array['S1']::text[]),
  ('4433EXPDA', 'Exploratory Data Analysis', 'Students learn exploratory data analysis methods for high-dimensional datasets, using visualization and statistical techniques to uncover relationships beyond simple two-variable plots.', 'https://studiegids.universiteitleiden.nl/en/courses/131646/exploratory-data-analysis', '#0ea5e9', 'chart', 6, array['S1']::text[]),
  ('4343FSWT6', 'Foundations of Software Testing', 'This course teaches software testing foundations, focusing on why faults arise, how testing reveals failures and how systematic techniques improve software reliability.', 'https://studiegids.universiteitleiden.nl/en/courses/131625/foundations-of-software-testing', '#2563eb', 'code', 6, array['S2']::text[]),
  ('4383HICNM', 'From Human Intelligence to Cognition in Nature and Machines', 'Students compare human cognition with intelligence in nature and machines, reflecting on recent AI advances and what they imply for understanding minds.', 'https://studiegids.universiteitleiden.nl/en/courses/131716/from-human-intelligence-to-cognition-in-nature-and-machines', '#7c3aed', 'book-open', 6, array['S2']::text[]),
  ('4343BSGBG', 'Global Business Game - CIO Simulation', 'Students are introduced to company management through a CIO-focused simulation game that connects business decisions, ICT strategy and organizational consequences.', 'https://studiegids.universiteitleiden.nl/en/courses/131662/global-business-game-cio-simulation', '#001158', 'book-open', 0, array['S1']::text[]),
  ('4343HIPX6', 'High Performance Computing', 'Students learn high-performance computing concepts, including supercomputer architectures, distributed and shared-memory programming, GPU optimization and performance-aware scientific computing.', 'https://studiegids.universiteitleiden.nl/en/courses/131605/high-performance-computing', '#ef4444', 'book-open', 6, array['S2']::text[]),
  ('4433HDDAN', 'High-dimensional data analysis', 'Students analyze high-dimensional biological and biomedical data, learning statistical methods for many variables, small sample sizes and complex dependency structures.', 'https://studiegids.universiteitleiden.nl/en/courses/131638/high-dimensional-data-analysis', '#14b8a6', 'chart', 6, array['S1']::text[]),
  ('4343BSICT', 'ICT Enabled Process Innovation', 'Students examine how ICT transforms organizational processes, focusing on process thinking, innovation and the redesign of business activities through information technologies.', 'https://studiegids.universiteitleiden.nl/en/courses/131664/ict-enabled-process-innovation', '#001158', 'book-open', 3, array['S1']::text[]),
  ('4343MMAV6', 'Image Analysis with Applications in Microscopy', 'Students learn image processing and analysis through microscopy applications, connecting image formation, computational methods and practical analysis of scientific image data.', 'https://studiegids.universiteitleiden.nl/en/courses/131524/image-analysis-with-applications-in-microscopy', '#84cc16', 'dna', 6, array['S2']::text[]),
  ('4343INFRX', 'Information Retrieval', 'Students study search and information access technologies, from classical retrieval models to modern large language model contexts and practical retrieval challenges.', 'https://studiegids.universiteitleiden.nl/en/courses/131626/information-retrieval', '#0ea5e9', 'chart', 6, array['S2']::text[]),
  ('4343ITDM6', 'Information Theoretic Data Mining', 'Students learn principled approaches for discovering structure in data, focusing on information-theoretic models, exploratory data mining and interpretable pattern discovery.', 'https://studiegids.universiteitleiden.nl/en/courses/131627/information-theoretic-data-mining', '#10b981', 'chart', 6, array['S2']::text[]),
  ('4343INDLX', 'Introduction to Deep Learning', 'This course introduces neural network concepts, deep learning architectures and computer vision applications, combining theory with practical understanding of modern deep models.', 'https://studiegids.universiteitleiden.nl/en/courses/131395/introduction-to-deep-learning', '#4f46e5', 'brain', 6, array['S1']::text[]),
  ('4343IRPRJ', 'Introductory Research Project (Bioinformatics)', 'Students complete a smaller research project in bioinformatics, gaining experience with scientific research, project planning, innovation and reporting before the master thesis.', 'https://studiegids.universiteitleiden.nl/en/courses/131640/introductory-research-project-bioinformatics', '#22c55e', 'dna', 18, array['S1', 'S2']::text[]),
  ('4433LGMO6', 'Linear and Generalized Linear Models', 'Students study linear regression, analysis of variance and generalized linear models for explaining how predictors influence quantitative or categorical response variables.', 'https://studiegids.universiteitleiden.nl/en/courses/131647/linear-and-generalized-linear-models', '#0ea5e9', 'book-open', 6, array['S1']::text[]),
  ('4343BSMLB', 'Machine Learning for Business Analytics', 'Students learn how machine learning supports business analytics, turning organizational data into predictive insights for decisions in business and government contexts.', 'https://studiegids.universiteitleiden.nl/en/courses/131542/machine-learning-for-business-analytics', '#f59e0b', 'brain', 3, array['S1']::text[]),
  ('4343BSMSE', 'Managing Software Evolution', 'Students examine why software becomes costly to evolve, studying maintenance, legacy systems, technical debt and strategies for managing long-term software change.', 'https://studiegids.universiteitleiden.nl/en/courses/131671/managing-software-evolution', '#2563eb', 'code', 3, array['S2']::text[]),
  ('4343MACLA', 'Master Class', 'A mandatory thesis-support course where Computer Science students discuss research progress, academic practice and thesis-related topics during regular master class meetings.', 'https://studiegids.universiteitleiden.nl/en/courses/131634/master-class', '#001158', 'graduation', 0, array['S1', 'S2']::text[]),
  ('4343BSMAC', 'Master Class Computer Science and Business Studies', 'Second-year Business Studies students prepare for internships and thesis work, covering research topics, host organizations, supervision, project execution and thesis expectations.', 'https://studiegids.universiteitleiden.nl/en/courses/132957/master-class-computer-science-and-business-studies', '#001158', 'graduation', 0, array['S1']::text[]),
  ('4343MRP22', 'Master''s Thesis Research Project (CS & BS)', 'Students complete the final thesis project for Computer Science and Business Studies, combining original research with a business research internship.', 'https://studiegids.universiteitleiden.nl/en/courses/132956/masters-thesis-research-project-cs-bs', '#f46e32', 'graduation', 22, array['S1', 'S2']::text[]),
  ('4343MRP30', 'Master''s Thesis Research Project (CS & SCS/EDU)', 'Students complete an original Computer Science thesis project for the Education or Science Communication tracks, contributing research under academic supervision.', 'https://studiegids.universiteitleiden.nl/en/courses/131641/masters-thesis-research-project-cs-scsedu', '#a16207', 'graduation', 30, array['S1', 'S2']::text[]),
  ('4343MRP42', 'Master''s Thesis Research Project (CS)', 'Students complete the main Computer Science thesis project, conducting original supervised research that forms the final stage of the MSc programme.', 'https://studiegids.universiteitleiden.nl/en/courses/131635/masters-thesis-research-project-cs', '#001158', 'graduation', 42, array['S1', 'S2']::text[]),
  ('4343BSMDS', 'Model-Driven Systems Engineering', 'Students learn conceptual modeling and model-driven engineering for large enterprise information systems, covering modeling notations, principles, tools and implementation approaches.', 'https://studiegids.universiteitleiden.nl/en/courses/131666/model-driven-systems-engineering', '#2563eb', 'chip', 6, array['S2']::text[]),
  ('4343MGAIX', 'Modern Game AI Algorithms', 'Students study modern game AI methods, including algorithms used in games and robotics, with emphasis on applying reinforcement learning to realistic game-playing problems.', 'https://studiegids.universiteitleiden.nl/en/courses/131628/modern-game-ai-algorithms', '#d946ef', 'book-open', 6, array['S2']::text[]),
  ('4343MOADX', 'Multicriteria Optimization and Decision Analysis', 'Students learn advanced optimization for problems with constraints and multiple objectives, combining computational methods with decision analysis and applied mathematics.', 'https://studiegids.universiteitleiden.nl/en/courses/131527/multicriteria-optimization-and-decision-analysis', '#06b6d4', 'book-open', 6, array['S2']::text[]),
  ('4343MMSY6', 'Multimedia Systems', 'ACS students study multimedia systems across storage, processing, transmission and presentation of media, connecting system design with practical multimedia applications.', 'https://studiegids.universiteitleiden.nl/en/courses/131600/multimedia-systems', '#f59e0b', 'chip', 6, array['S1']::text[]),
  ('4343MMEBX', 'Multimodal Models for Ecology and Biodiversity', 'Students learn multimodal modeling for biodiversity monitoring, combining images, audio and biological measurements to improve automated ecological analysis systems.', 'https://studiegids.universiteitleiden.nl/en/courses/135828/multimodal-models-for-ecology-and-biodiversity', '#84cc16', 'dna', 6, array['S2']::text[]),
  ('4373MUMAB', 'Multiscale Mathematical Biology (BM)', 'Students use mathematical and computational models to study biological systems across scales, connecting biological questions with applied mathematical problem-solving.', 'https://studiegids.universiteitleiden.nl/en/courses/130756/multiscale-mathematical-biology-bm', '#22c55e', 'dna', 6, array['S1']::text[]),
  ('4032NLP6X', 'Natural Language Processing', 'Students learn core natural language processing techniques at the intersection of computer science, linguistics and AI, with attention to modern language technologies.', 'https://studiegids.universiteitleiden.nl/en/courses/131074/natural-language-processing', '#8b5cf6', 'book-open', 6, array['S1', 'S2']::text[]),
  ('4343NLPSG', 'Natural Language Processing for Social Good', 'Students study NLP methods for socially relevant applications, examining how language technologies can support communication, access and analysis in public-interest domains.', 'https://studiegids.universiteitleiden.nl/en/courses/135833/natural-language-processing-for-social-good', '#a855f7', 'book-open', 6, array['S2']::text[]),
  ('4343PROFX', 'Proof Formalisation', 'Students learn how mathematical proofs can be represented and checked by machines, studying formal proof systems and proof assistants for reliable reasoning.', 'https://studiegids.universiteitleiden.nl/en/courses/131629/proof-formalisation', '#3b82f6', 'book-open', 6, array['S2']::text[]),
  ('4343QUALG', 'Quantum Algorithms', 'Students study quantum computation and key quantum algorithms, learning how this model differs from classical computing and where it may offer advantages.', 'https://studiegids.universiteitleiden.nl/en/courses/131612/quantum-algorithms', '#6366f1', 'atom', 6, array['S1']::text[]),
  ('4343RECSX', 'Recommender Systems', 'Students learn how AI-driven recommender systems model user preferences, personalize choices and raise practical issues around data, algorithms, evaluation and impact.', 'https://studiegids.universiteitleiden.nl/en/courses/131630/recommender-systems', '#14b8a6', 'chart', 6, array['S2']::text[]),
  ('4343BSRGD', 'Regulatory Governance and Data Science', 'Students examine data governance for AI, focusing on data quality, control, regulation and the societal and business challenges of responsible data use.', 'https://studiegids.universiteitleiden.nl/en/courses/131675/regulatory-governance-and-data-science', '#001158', 'chart', 6, array['S1']::text[]),
  ('4343RINLX', 'Reinforcement Learning', 'Students learn reinforcement learning theory and algorithms, with attention to deep reinforcement learning successes in games, robotics and sequential decision-making problems.', 'https://studiegids.universiteitleiden.nl/en/courses/131396/reinforcement-learning', '#4f46e5', 'brain', 6, array['S2']::text[]),
  ('4343ROBO6', 'Robotics', 'Students study modern robot architectures, sensors, actuators, navigation, mapping, manipulation, human-robot interaction and adaptive behavior in natural environments.', 'https://studiegids.universiteitleiden.nl/en/courses/131631/robotics', '#d946ef', 'brain', 6, array['S2']::text[]),
  ('4343BSRPA', 'Role of IT in Public Administration', 'Students learn how public-sector characteristics shape ICT projects, covering public administration theory, leadership, regulation, collaboration, governance and data-era policy challenges.', 'https://studiegids.universiteitleiden.nl/en/courses/131674/role-of-it-in-public-administration', '#001158', 'book-open', 6, array['S2']::text[]),
  ('4343SADRL', 'Seminar Advanced Deep Reinforcement Learning', 'Students study recent deep reinforcement learning papers, replicate results in small groups, present progress and write a research-style report.', 'https://studiegids.universiteitleiden.nl/en/courses/131613/seminar-advanced-deep-reinforcement-learning', '#4f46e5', 'brain', 6, array['S1']::text[]),
  ('4343SADL6', 'Seminar Advances in Deep Learning', 'Students work in groups on recent deep learning papers, replicating and extending results while learning current topics through lectures and peer presentations.', 'https://studiegids.universiteitleiden.nl/en/courses/131397/seminar-advances-in-deep-learning', '#4f46e5', 'brain', 6, array['S2']::text[]),
  ('4343SMTAI', 'Seminar Trustworthy Artificial Intelligence', 'Students investigate trustworthy AI topics such as robustness, verification, explainability, bias and privacy through recent research papers, presentations and group reports.', 'https://studiegids.universiteitleiden.nl/en/courses/131614/seminar-trustworthy-artificial-intelligence', '#7c3aed', 'brain', 6, array['S1']::text[]),
  ('4343SNACS', 'Social Network Analysis for Computer Scientists', 'Students study network science for social and technical systems, covering network models, algorithms, visualization, epidemics, pattern detection and computational complexity.', 'https://studiegids.universiteitleiden.nl/en/courses/123612/complex-networks-bm', '#2563eb', 'network', 6, array['S1']::text[]),
  ('4343BSSDP', 'Software Development and Product Management', 'Students learn software product management and development, covering product strategy, lifecycle management, Scrum, project planning, quality, risk and user expectations.', 'https://studiegids.universiteitleiden.nl/en/courses/131616/software-development-and-product-management', '#0ea5e9', 'code', 6, array['S1']::text[]),
  ('4343SWVRX', 'Software Verification', 'Students study formal verification, especially model checking, to prove correctness of software and hardware systems beyond what testing alone can guarantee.', 'https://studiegids.universiteitleiden.nl/en/courses/131632/software-verification', '#ef4444', 'code', 6, array['S2']::text[]),
  ('4343SPDSX', 'Sports Data Science', 'Students learn how data science supports sports analysis, covering training optimization, injury prevention, tactical decisions, time series, feature construction and subgroup discovery.', 'https://studiegids.universiteitleiden.nl/en/courses/131633/sports-data-science', '#f59e0b', 'chart', 6, array['S2']::text[]),
  ('4433STATG', 'Statistical genetics', 'Students model genetic data for life science applications, studying pedigrees, linkage, heritability, association studies, Mendelian randomization and gene expression analysis.', 'https://studiegids.universiteitleiden.nl/en/courses/131639/statistical-genetics', '#84cc16', 'book-open', 6, array['S1']::text[]),
  ('4433STATL', 'Statistical Learning', 'Students learn supervised and unsupervised statistical learning methods, including regression, classifiers, clustering, dimension reduction, model selection and evaluation.', 'https://studiegids.universiteitleiden.nl/en/courses/131648/statistical-learning', '#10b981', 'brain', 6, array['S2']::text[]),
  ('4343SYSSS', 'System and Software Security', 'Students study software and hardware security, covering vulnerabilities, mitigations, secure development, processor-level attacks, roots of trust and research-oriented group projects.', 'https://studiegids.universiteitleiden.nl/en/courses/131601/system-and-software-security', '#e11d48', 'shield', 6, array['S1']::text[]),
  ('4343TXTMX', 'Text Mining', 'Students learn text mining foundations and applications, including text representation, classification, annotation, transformer models, information extraction, topic modeling, summarization and sentiment analysis.', 'https://studiegids.universiteitleiden.nl/en/courses/131617/text-mining', '#14b8a6', 'chart', 6, array['S1']::text[]),
  ('4343URBC6', 'Urban computing', 'Students study urban computing with spatio-temporal data mining, learning how computing methods address mobility, traffic, pollution and environmental challenges.', 'https://studiegids.universiteitleiden.nl/en/courses/131618/urban-computing', '#0ea5e9', 'book-open', 6, array['S1']::text[]),
  ('4383VGFR6', 'Video Games for Research', 'Students learn to design and conduct research with video games or interactive experiences, combining game studies, development practice and applied research design.', 'https://studiegids.universiteitleiden.nl/en/courses/131619/video-games-for-research', '#d946ef', 'graduation', 6, array['S1']::text[])
on conflict (code) do update
set title = excluded.title,
    description = excluded.description,
    studiegids_url = excluded.studiegids_url,
    color = excluded.color,
    icon = excluded.icon,
    ec = excluded.ec,
    offered_semesters = excluded.offered_semesters;

with mapping (course_code, spec_code, role) as (values
  ('4343ADVDX', 'acs', 'elective'),
  ('4343ADVDX', 'ai', 'elective'),
  ('4343ADVDX', 'bioinf', 'core'),
  ('4343ADVDX', 'csbs', 'elective'),
  ('4343ADVDX', 'cse', 'elective'),
  ('4343ADVDX', 'ds', 'core'),
  ('4343ADVDX', 'foc', 'elective'),
  ('4343ADVDX', 'scss', 'elective'),
  ('4343AIART', 'acs', 'elective'),
  ('4343AIART', 'ai', 'elective'),
  ('4343AIART', 'csbs', 'elective'),
  ('4343AIART', 'cse', 'elective'),
  ('4343AIART', 'ds', 'elective'),
  ('4343AIART', 'foc', 'elective'),
  ('4343AIART', 'scss', 'elective'),
  ('4343AISOC', 'ai', 'core'),
  ('4343APQALY', 'acs', 'elective'),
  ('4343APQALY', 'ai', 'elective'),
  ('4343APQALY', 'csbs', 'elective'),
  ('4343APQALY', 'cse', 'elective'),
  ('4343APQALY', 'ds', 'elective'),
  ('4343APQALY', 'foc', 'elective'),
  ('4343APQALY', 'scss', 'elective'),
  ('4383ARCR3', 'ai', 'elective'),
  ('4343AUDIO', 'acs', 'elective'),
  ('4343AUDIO', 'ai', 'elective'),
  ('4343AUDIO', 'csbs', 'elective'),
  ('4343AUDIO', 'cse', 'elective'),
  ('4343AUDIO', 'ds', 'elective'),
  ('4343AUDIO', 'foc', 'elective'),
  ('4343AUDIO', 'scss', 'elective'),
  ('4343AUTMX', 'acs', 'elective'),
  ('4343AUTMX', 'ai', 'core'),
  ('4343AUTMX', 'bioinf', 'elective'),
  ('4343AUTMX', 'csbs', 'elective'),
  ('4343AUTMX', 'cse', 'elective'),
  ('4343AUTMX', 'ds', 'elective'),
  ('4343AUTMX', 'foc', 'elective'),
  ('4343AUTMX', 'scss', 'elective'),
  ('4343BAYOP', 'acs', 'elective'),
  ('4343BAYOP', 'ai', 'elective'),
  ('4343BAYOP', 'bioinf', 'elective'),
  ('4343BAYOP', 'csbs', 'elective'),
  ('4343BAYOP', 'cse', 'elective'),
  ('4343BAYOP', 'ds', 'elective'),
  ('4343BAYOP', 'foc', 'elective'),
  ('4343BAYOP', 'scss', 'elective'),
  ('4343BIOMD', 'acs', 'elective'),
  ('4343BIOMD', 'ai', 'elective'),
  ('4343BIOMD', 'bioinf', 'core'),
  ('4343BIOMD', 'csbs', 'elective'),
  ('4343BIOMD', 'cse', 'elective'),
  ('4343BIOMD', 'ds', 'elective'),
  ('4343BIOMD', 'foc', 'elective'),
  ('4343BIOMD', 'scss', 'elective'),
  ('4343BICAI', 'acs', 'elective'),
  ('4343BICAI', 'ai', 'elective'),
  ('4343BICAI', 'bioinf', 'elective'),
  ('4343BICAI', 'csbs', 'elective'),
  ('4343BICAI', 'cse', 'elective'),
  ('4343BICAI', 'ds', 'elective'),
  ('4343BICAI', 'foc', 'elective'),
  ('4343BICAI', 'scss', 'elective'),
  ('4343BSCC4', 'csbs', 'core'),
  ('4343CICSX', 'acs', 'elective'),
  ('4343CICSX', 'ai', 'elective'),
  ('4343CICSX', 'csbs', 'elective'),
  ('4343CICSX', 'cse', 'elective'),
  ('4343CICSX', 'ds', 'elective'),
  ('4343CICSX', 'foc', 'elective'),
  ('4343CICSX', 'scss', 'elective'),
  ('4343CLCMX', 'acs', 'core'),
  ('4343CLCMX', 'ai', 'elective'),
  ('4343CLCMX', 'bioinf', 'elective'),
  ('4343CLCMX', 'cse', 'elective'),
  ('4343CLCMX', 'ds', 'elective'),
  ('4343CLCMX', 'foc', 'elective'),
  ('4343CLCMX', 'scss', 'elective'),
  ('4609COMNWY', 'acs', 'elective'),
  ('4609COMNWY', 'ai', 'elective'),
  ('4609COMNWY', 'bioinf', 'elective'),
  ('4609COMNWY', 'csbs', 'elective'),
  ('4609COMNWY', 'cse', 'elective'),
  ('4609COMNWY', 'ds', 'elective'),
  ('4609COMNWY', 'foc', 'elective'),
  ('4609COMNWY', 'scss', 'elective'),
  ('4383COMCR', 'acs', 'elective'),
  ('4383COMCR', 'ai', 'core'),
  ('4383COMCR', 'csbs', 'elective'),
  ('4383COMCR', 'cse', 'elective'),
  ('4383COMCR', 'ds', 'elective'),
  ('4383COMCR', 'foc', 'elective'),
  ('4383COMCR', 'scss', 'elective'),
  ('4343CIMTO', 'acs', 'elective'),
  ('4343CIMTO', 'ai', 'elective'),
  ('4343CIMTO', 'bioinf', 'elective'),
  ('4343CIMTO', 'csbs', 'elective'),
  ('4343CIMTO', 'cse', 'elective'),
  ('4343CIMTO', 'ds', 'elective'),
  ('4343CIMTO', 'foc', 'elective'),
  ('4343CIMTO', 'scss', 'elective'),
  ('4343CMS6X', 'acs', 'elective'),
  ('4343CMS6X', 'ai', 'elective'),
  ('4343CMS6X', 'csbs', 'elective'),
  ('4343CMS6X', 'cse', 'elective'),
  ('4343CMS6X', 'ds', 'elective'),
  ('4343CMS6X', 'foc', 'core'),
  ('4343CMS6X', 'scss', 'elective'),
  ('4433COMST', 'ds', 'elective'),
  ('4343CRYPE', 'acs', 'elective'),
  ('4343CRYPE', 'ai', 'elective'),
  ('4343CRYPE', 'csbs', 'elective'),
  ('4343CRYPE', 'cse', 'elective'),
  ('4343CRYPE', 'ds', 'elective'),
  ('4343CRYPE', 'foc', 'elective'),
  ('4343CRYPE', 'scss', 'elective'),
  ('4343BSCSM', 'csbs', 'elective'),
  ('4343DASPR', 'csbs', 'elective'),
  ('4343DASPR', 'ds', 'elective'),
  ('4433DATVI', 'ds', 'elective'),
  ('4343DDORW', 'acs', 'elective'),
  ('4343DDORW', 'ai', 'elective'),
  ('4343DDORW', 'csbs', 'elective'),
  ('4343DDORW', 'cse', 'elective'),
  ('4343DDORW', 'ds', 'elective'),
  ('4343DDORW', 'foc', 'elective'),
  ('4343DDORW', 'scss', 'elective'),
  ('4343BSDPM', 'acs', 'elective'),
  ('4343BSDPM', 'ai', 'elective'),
  ('4343BSDPM', 'csbs', 'elective'),
  ('4343BSDPM', 'cse', 'elective'),
  ('4343BSDPM', 'ds', 'elective'),
  ('4343BSDPM', 'foc', 'elective'),
  ('4343BSDPM', 'scss', 'elective'),
  ('4343DISYX', 'acs', 'core'),
  ('4343DISYX', 'ai', 'elective'),
  ('4343DISYX', 'csbs', 'elective'),
  ('4343DISYX', 'cse', 'elective'),
  ('4343DISYX', 'ds', 'elective'),
  ('4343DISYX', 'foc', 'elective'),
  ('4343DISYX', 'scss', 'elective'),
  ('4343EMBSS', 'acs', 'core'),
  ('4343EMBSS', 'ai', 'elective'),
  ('4343EMBSS', 'csbs', 'elective'),
  ('4343EMBSS', 'cse', 'elective'),
  ('4343EMBSS', 'ds', 'elective'),
  ('4343EMBSS', 'foc', 'elective'),
  ('4343EMBSS', 'scss', 'elective'),
  ('4343BSEA6', 'csbs', 'core'),
  ('4343EVALX', 'acs', 'elective'),
  ('4343EVALX', 'ai', 'core'),
  ('4343EVALX', 'bioinf', 'core'),
  ('4343EVALX', 'csbs', 'elective'),
  ('4343EVALX', 'cse', 'elective'),
  ('4343EVALX', 'ds', 'elective'),
  ('4343EVALX', 'foc', 'elective'),
  ('4343EVALX', 'scss', 'elective'),
  ('4433EXPDA', 'ds', 'elective'),
  ('4343FSWT6', 'acs', 'elective'),
  ('4343FSWT6', 'ai', 'elective'),
  ('4343FSWT6', 'csbs', 'elective'),
  ('4343FSWT6', 'cse', 'elective'),
  ('4343FSWT6', 'ds', 'elective'),
  ('4343FSWT6', 'foc', 'core'),
  ('4343FSWT6', 'scss', 'elective'),
  ('4383HICNM', 'ai', 'elective'),
  ('4343BSGBG', 'csbs', 'core'),
  ('4343HIPX6', 'acs', 'core'),
  ('4343HIPX6', 'ai', 'elective'),
  ('4343HIPX6', 'csbs', 'elective'),
  ('4343HIPX6', 'cse', 'elective'),
  ('4343HIPX6', 'ds', 'elective'),
  ('4343HIPX6', 'foc', 'elective'),
  ('4343HIPX6', 'scss', 'elective'),
  ('4433HDDAN', 'bioinf', 'elective'),
  ('4343BSICT', 'csbs', 'elective'),
  ('4343MMAV6', 'acs', 'elective'),
  ('4343MMAV6', 'ai', 'elective'),
  ('4343MMAV6', 'bioinf', 'core'),
  ('4343MMAV6', 'csbs', 'elective'),
  ('4343MMAV6', 'cse', 'elective'),
  ('4343MMAV6', 'ds', 'elective'),
  ('4343MMAV6', 'foc', 'elective'),
  ('4343MMAV6', 'scss', 'elective'),
  ('4343INFRX', 'acs', 'elective'),
  ('4343INFRX', 'ai', 'elective'),
  ('4343INFRX', 'csbs', 'elective'),
  ('4343INFRX', 'cse', 'elective'),
  ('4343INFRX', 'ds', 'core'),
  ('4343INFRX', 'foc', 'elective'),
  ('4343INFRX', 'scss', 'elective'),
  ('4343ITDM6', 'acs', 'elective'),
  ('4343ITDM6', 'ai', 'elective'),
  ('4343ITDM6', 'csbs', 'elective'),
  ('4343ITDM6', 'cse', 'elective'),
  ('4343ITDM6', 'ds', 'elective'),
  ('4343ITDM6', 'foc', 'elective'),
  ('4343ITDM6', 'scss', 'elective'),
  ('4343INDLX', 'acs', 'elective'),
  ('4343INDLX', 'ai', 'core'),
  ('4343INDLX', 'bioinf', 'core'),
  ('4343INDLX', 'csbs', 'elective'),
  ('4343INDLX', 'cse', 'elective'),
  ('4343INDLX', 'ds', 'core'),
  ('4343INDLX', 'foc', 'elective'),
  ('4343INDLX', 'scss', 'elective'),
  ('4343IRPRJ', 'bioinf', 'elective'),
  ('4433LGMO6', 'ds', 'elective'),
  ('4343BSMLB', 'csbs', 'elective'),
  ('4343BSMSE', 'csbs', 'elective'),
  ('4343MACLA', 'acs', 'elective'),
  ('4343MACLA', 'ai', 'elective'),
  ('4343MACLA', 'bioinf', 'elective'),
  ('4343MACLA', 'cse', 'elective'),
  ('4343MACLA', 'ds', 'elective'),
  ('4343MACLA', 'foc', 'elective'),
  ('4343MACLA', 'scss', 'elective'),
  ('4343BSMAC', 'csbs', 'elective'),
  ('4343MRP22', 'csbs', 'elective'),
  ('4343MRP30', 'cse', 'elective'),
  ('4343MRP30', 'scss', 'elective'),
  ('4343MRP42', 'acs', 'elective'),
  ('4343MRP42', 'ai', 'elective'),
  ('4343MRP42', 'bioinf', 'elective'),
  ('4343MRP42', 'ds', 'elective'),
  ('4343MRP42', 'foc', 'elective'),
  ('4343BSMDS', 'csbs', 'core'),
  ('4343MGAIX', 'acs', 'elective'),
  ('4343MGAIX', 'ai', 'core'),
  ('4343MGAIX', 'csbs', 'elective'),
  ('4343MGAIX', 'cse', 'elective'),
  ('4343MGAIX', 'ds', 'elective'),
  ('4343MGAIX', 'foc', 'core'),
  ('4343MGAIX', 'scss', 'elective'),
  ('4343MOADX', 'acs', 'elective'),
  ('4343MOADX', 'ai', 'core'),
  ('4343MOADX', 'bioinf', 'elective'),
  ('4343MOADX', 'csbs', 'elective'),
  ('4343MOADX', 'cse', 'elective'),
  ('4343MOADX', 'ds', 'elective'),
  ('4343MOADX', 'foc', 'elective'),
  ('4343MOADX', 'scss', 'elective'),
  ('4343MMSY6', 'acs', 'core'),
  ('4343MMSY6', 'ai', 'elective'),
  ('4343MMSY6', 'csbs', 'elective'),
  ('4343MMSY6', 'cse', 'elective'),
  ('4343MMSY6', 'ds', 'elective'),
  ('4343MMSY6', 'foc', 'elective'),
  ('4343MMSY6', 'scss', 'elective'),
  ('4343MMEBX', 'acs', 'elective'),
  ('4343MMEBX', 'ai', 'elective'),
  ('4343MMEBX', 'bioinf', 'core'),
  ('4343MMEBX', 'csbs', 'elective'),
  ('4343MMEBX', 'cse', 'elective'),
  ('4343MMEBX', 'ds', 'elective'),
  ('4343MMEBX', 'foc', 'elective'),
  ('4343MMEBX', 'scss', 'elective'),
  ('4373MUMAB', 'bioinf', 'elective'),
  ('4032NLP6X', 'csbs', 'elective'),
  ('4343NLPSG', 'acs', 'elective'),
  ('4343NLPSG', 'ai', 'elective'),
  ('4343NLPSG', 'cse', 'elective'),
  ('4343NLPSG', 'ds', 'elective'),
  ('4343NLPSG', 'foc', 'elective'),
  ('4343NLPSG', 'scss', 'elective'),
  ('4343PROFX', 'acs', 'elective'),
  ('4343PROFX', 'ai', 'elective'),
  ('4343PROFX', 'csbs', 'elective'),
  ('4343PROFX', 'cse', 'elective'),
  ('4343PROFX', 'ds', 'elective'),
  ('4343PROFX', 'foc', 'core'),
  ('4343PROFX', 'scss', 'elective'),
  ('4343QUALG', 'acs', 'elective'),
  ('4343QUALG', 'ai', 'elective'),
  ('4343QUALG', 'bioinf', 'elective'),
  ('4343QUALG', 'csbs', 'elective'),
  ('4343QUALG', 'cse', 'elective'),
  ('4343QUALG', 'ds', 'elective'),
  ('4343QUALG', 'foc', 'core'),
  ('4343QUALG', 'scss', 'elective'),
  ('4343RECSX', 'acs', 'elective'),
  ('4343RECSX', 'ai', 'elective'),
  ('4343RECSX', 'csbs', 'elective'),
  ('4343RECSX', 'cse', 'elective'),
  ('4343RECSX', 'ds', 'elective'),
  ('4343RECSX', 'foc', 'elective'),
  ('4343RECSX', 'scss', 'elective'),
  ('4343BSRGD', 'csbs', 'elective'),
  ('4343BSRGD', 'ds', 'elective'),
  ('4343RINLX', 'acs', 'elective'),
  ('4343RINLX', 'ai', 'core'),
  ('4343RINLX', 'bioinf', 'elective'),
  ('4343RINLX', 'csbs', 'elective'),
  ('4343RINLX', 'cse', 'elective'),
  ('4343RINLX', 'ds', 'core'),
  ('4343RINLX', 'foc', 'elective'),
  ('4343RINLX', 'scss', 'elective'),
  ('4343ROBO6', 'acs', 'elective'),
  ('4343ROBO6', 'ai', 'elective'),
  ('4343ROBO6', 'csbs', 'elective'),
  ('4343ROBO6', 'cse', 'elective'),
  ('4343ROBO6', 'ds', 'elective'),
  ('4343ROBO6', 'foc', 'elective'),
  ('4343ROBO6', 'scss', 'elective'),
  ('4343BSRPA', 'csbs', 'elective'),
  ('4343SADRL', 'acs', 'elective'),
  ('4343SADRL', 'ai', 'elective'),
  ('4343SADRL', 'bioinf', 'elective'),
  ('4343SADRL', 'csbs', 'elective'),
  ('4343SADRL', 'cse', 'elective'),
  ('4343SADRL', 'ds', 'elective'),
  ('4343SADRL', 'foc', 'elective'),
  ('4343SADRL', 'scss', 'elective'),
  ('4343SADL6', 'acs', 'elective'),
  ('4343SADL6', 'ai', 'elective'),
  ('4343SADL6', 'bioinf', 'elective'),
  ('4343SADL6', 'csbs', 'elective'),
  ('4343SADL6', 'cse', 'elective'),
  ('4343SADL6', 'ds', 'elective'),
  ('4343SADL6', 'foc', 'elective'),
  ('4343SADL6', 'scss', 'elective'),
  ('4343SMTAI', 'acs', 'elective'),
  ('4343SMTAI', 'ai', 'elective'),
  ('4343SMTAI', 'bioinf', 'elective'),
  ('4343SMTAI', 'csbs', 'elective'),
  ('4343SMTAI', 'cse', 'elective'),
  ('4343SMTAI', 'ds', 'elective'),
  ('4343SMTAI', 'foc', 'elective'),
  ('4343SMTAI', 'scss', 'elective'),
  ('4343SNACS', 'acs', 'elective'),
  ('4343SNACS', 'ai', 'elective'),
  ('4343SNACS', 'bioinf', 'elective'),
  ('4343SNACS', 'csbs', 'elective'),
  ('4343SNACS', 'cse', 'elective'),
  ('4343SNACS', 'ds', 'core'),
  ('4343SNACS', 'foc', 'elective'),
  ('4343SNACS', 'scss', 'elective'),
  ('4343BSSDP', 'acs', 'elective'),
  ('4343BSSDP', 'ai', 'elective'),
  ('4343BSSDP', 'csbs', 'core'),
  ('4343BSSDP', 'cse', 'elective'),
  ('4343BSSDP', 'ds', 'elective'),
  ('4343BSSDP', 'foc', 'elective'),
  ('4343BSSDP', 'scss', 'elective'),
  ('4343SWVRX', 'acs', 'elective'),
  ('4343SWVRX', 'ai', 'elective'),
  ('4343SWVRX', 'csbs', 'elective'),
  ('4343SWVRX', 'cse', 'elective'),
  ('4343SWVRX', 'ds', 'elective'),
  ('4343SWVRX', 'foc', 'core'),
  ('4343SWVRX', 'scss', 'elective'),
  ('4343SPDSX', 'acs', 'elective'),
  ('4343SPDSX', 'ai', 'elective'),
  ('4343SPDSX', 'csbs', 'elective'),
  ('4343SPDSX', 'cse', 'elective'),
  ('4343SPDSX', 'ds', 'elective'),
  ('4343SPDSX', 'foc', 'elective'),
  ('4343SPDSX', 'scss', 'elective'),
  ('4433STATG', 'bioinf', 'elective'),
  ('4433STATL', 'ds', 'elective'),
  ('4343SYSSS', 'acs', 'core'),
  ('4343SYSSS', 'ai', 'elective'),
  ('4343SYSSS', 'csbs', 'elective'),
  ('4343SYSSS', 'cse', 'elective'),
  ('4343SYSSS', 'ds', 'elective'),
  ('4343SYSSS', 'foc', 'elective'),
  ('4343SYSSS', 'scss', 'elective'),
  ('4343TXTMX', 'acs', 'elective'),
  ('4343TXTMX', 'ai', 'elective'),
  ('4343TXTMX', 'bioinf', 'elective'),
  ('4343TXTMX', 'csbs', 'elective'),
  ('4343TXTMX', 'cse', 'elective'),
  ('4343TXTMX', 'ds', 'core'),
  ('4343TXTMX', 'foc', 'elective'),
  ('4343TXTMX', 'scss', 'elective'),
  ('4343URBC6', 'acs', 'elective'),
  ('4343URBC6', 'ai', 'elective'),
  ('4343URBC6', 'csbs', 'elective'),
  ('4343URBC6', 'cse', 'elective'),
  ('4343URBC6', 'ds', 'elective'),
  ('4343URBC6', 'foc', 'elective'),
  ('4343URBC6', 'scss', 'elective'),
  ('4383VGFR6', 'acs', 'elective'),
  ('4383VGFR6', 'ai', 'elective'),
  ('4383VGFR6', 'csbs', 'elective'),
  ('4383VGFR6', 'cse', 'elective'),
  ('4383VGFR6', 'ds', 'elective'),
  ('4383VGFR6', 'foc', 'elective'),
  ('4383VGFR6', 'scss', 'elective')
)
insert into public.course_specializations (course_id, specialization_id, role)
select c.id, s.id, m.role
from mapping m
join public.courses c on c.code = m.course_code
join public.specializations s on s.code = m.spec_code
on conflict (course_id, specialization_id) do update
set role = excluded.role;

insert into public.admins (email) values
  ('s.r.de.groot.2@umail.leidenuniv.nl'),
  ('s3569829@umail.leidenuniv.nl')
on conflict (email) do nothing;
