insert into public.admins (email) values
  ('s3569829@umail.leidenuniv.nl')
on conflict (email) do nothing;

with summaries (code, description) as (values
  ('4032NLP6X', 'Students learn core natural language processing techniques at the intersection of computer science, linguistics and AI, with attention to modern language technologies.'),
  ('4343ADVDX', 'Students learn modern data mining methods for massive datasets, including streaming data, similarity search, anomaly detection, clustering, recommender systems and dimensionality reduction.'),
  ('4343AIART', 'This course combines generative AI techniques with critical reflection on creativity, authorship, aesthetics, ethics and the changing role of machines in artistic practice.'),
  ('4343AISOC', 'Students examine AI through social, political, ethical and environmental lenses, then apply these perspectives to real domains through a speculative hands-on project.'),
  ('4343APQALY', 'An advanced quantum computing course focused on practical algorithm design for chemistry, physics, machine learning and the error correction methods needed for noisy devices.'),
  ('4343AUDIO', 'This seminar covers speech recognition, audio synthesis and content-based audio retrieval through lectures, workshops, literature study, student presentations and final project demos.'),
  ('4343AUTMX', 'Students study how AutoML selects algorithms and tunes hyperparameters so machine learning systems can achieve strong predictive performance on new datasets.'),
  ('4343BAYOP', 'This course teaches Bayesian optimization for expensive black-box functions, covering Gaussian processes, acquisition functions, noisy observations, constraints and practical Python applications.'),
  ('4343BICAI', 'Students investigate efficient AI inspired by the brain, including compression, quantization, neuromorphic computing and hardware approaches for low-power machine learning.'),
  ('4343BIOMD', 'Students model biological processes with formal computational frameworks such as Boolean networks and Petri nets, combining lectures, tool practice and interdisciplinary project work.'),
  ('4343BSCC4', 'Second-year students apply earlier business and IT knowledge to real or realistic company cases, analyzing problems and presenting practical recommendations to management.'),
  ('4343BSCSM', 'A management-oriented cybersecurity course for future CIOs, covering organizational risk, governance, policy and the business impact of ICT security decisions.'),
  ('4343BSDPM', 'Students examine how governments use data for policy, focusing on digital-era governance, data readiness, infrastructure, accountability and technology-driven public innovation.'),
  ('4343BSEA6', 'Students learn enterprise architecture methods and models for designing coherent organizations, aligning business processes, information systems, principles and implementation choices.'),
  ('4343BSGBG', 'Students are introduced to company management through a CIO-focused simulation game that connects business decisions, ICT strategy and organizational consequences.'),
  ('4343BSICT', 'Students examine how ICT transforms organizational processes, focusing on process thinking, innovation and the redesign of business activities through information technologies.'),
  ('4343BSMAC', 'Second-year Business Studies students prepare for internships and thesis work, covering research topics, host organizations, supervision, project execution and thesis expectations.'),
  ('4343BSMDS', 'Students learn conceptual modeling and model-driven engineering for large enterprise information systems, covering modeling notations, principles, tools and implementation approaches.'),
  ('4343BSMLB', 'Students learn how machine learning supports business analytics, turning organizational data into predictive insights for decisions in business and government contexts.'),
  ('4343BSMSE', 'Students examine why software becomes costly to evolve, studying maintenance, legacy systems, technical debt and strategies for managing long-term software change.'),
  ('4343BSRGD', 'Students examine data governance for AI, focusing on data quality, control, regulation and the societal and business challenges of responsible data use.'),
  ('4343BSRPA', 'Students learn how public-sector characteristics shape ICT projects, covering public administration theory, leadership, regulation, collaboration, governance and data-era policy challenges.'),
  ('4343BSSDP', 'Students learn software product management and development, covering product strategy, lifecycle management, Scrum, project planning, quality, risk and user expectations.'),
  ('4343CICSX', 'Students learn causal inference for machine learning, using structural causal models, potential outcomes, interventions, counterfactuals and data-driven causal discovery methods.'),
  ('4343CIMTO', 'This seminar introduces computational imaging and tomography, connecting physical measurement models, inverse problems, algorithms, high-performance computing and advanced research literature.'),
  ('4343CLCMX', 'This course surveys cloud computing from infrastructure and deployment models to scalability, resource management, cloud programming, research papers and hands-on platform assignments.'),
  ('4343CMS6X', 'Students study computational models and programming language semantics, using functional, probabilistic and categorical perspectives alongside Haskell assignments and a research project.'),
  ('4343CRYPE', 'Students study secure implementation of cryptographic algorithms in hardware and software, considering design constraints such as performance, resources, energy use and side-channel risks.'),
  ('4343DASPR', 'Students work on real Fieldlab data problems, moving from problem exploration and data quality assessment to solution design and applied data science practice.'),
  ('4343DDORW', 'Students model and solve real-world optimization problems with constraints, uncertainty and data, connecting theoretical foundations to practical decision-making applications.'),
  ('4343DISYX', 'This course covers the principles behind distributed systems that power social networks, government services and streaming platforms, with attention to reliability and coordination.'),
  ('4343EMBSS', 'Students study embedded systems that interact tightly with physical environments, from appliances and medical devices to portable systems, with focus on architecture and software constraints.'),
  ('4343EVALX', 'Students study evolutionary algorithms that search for solutions through population-based variation and selection, applying evolutionary computation to complex optimization problems.'),
  ('4343FSWT6', 'This course teaches software testing foundations, focusing on why faults arise, how testing reveals failures and how systematic techniques improve software reliability.'),
  ('4343HIPX6', 'Students learn high-performance computing concepts, including supercomputer architectures, distributed and shared-memory programming, GPU optimization and performance-aware scientific computing.'),
  ('4343INDLX', 'This course introduces neural network concepts, deep learning architectures and computer vision applications, combining theory with practical understanding of modern deep models.'),
  ('4343INFRX', 'Students study search and information access technologies, from classical retrieval models to modern large language model contexts and practical retrieval challenges.'),
  ('4343IRPRJ', 'Students complete a smaller research project in bioinformatics, gaining experience with scientific research, project planning, innovation and reporting before the master thesis.'),
  ('4343ITDM6', 'Students learn principled approaches for discovering structure in data, focusing on information-theoretic models, exploratory data mining and interpretable pattern discovery.'),
  ('4343MACLA', 'A mandatory thesis-support course where Computer Science students discuss research progress, academic practice and thesis-related topics during regular master class meetings.'),
  ('4343MGAIX', 'Students study modern game AI methods, including algorithms used in games and robotics, with emphasis on applying reinforcement learning to realistic game-playing problems.'),
  ('4343MMAV6', 'Students learn image processing and analysis through microscopy applications, connecting image formation, computational methods and practical analysis of scientific image data.'),
  ('4343MMEBX', 'Students learn multimodal modeling for biodiversity monitoring, combining images, audio and biological measurements to improve automated ecological analysis systems.'),
  ('4343MMSY6', 'ACS students study multimedia systems across storage, processing, transmission and presentation of media, connecting system design with practical multimedia applications.'),
  ('4343MOADX', 'Students learn advanced optimization for problems with constraints and multiple objectives, combining computational methods with decision analysis and applied mathematics.'),
  ('4343MRP22', 'Students complete the final thesis project for Computer Science and Business Studies, combining original research with a business research internship.'),
  ('4343MRP30', 'Students complete an original Computer Science thesis project for the Education or Science Communication tracks, contributing research under academic supervision.'),
  ('4343MRP42', 'Students complete the main Computer Science thesis project, conducting original supervised research that forms the final stage of the MSc programme.'),
  ('4343NLPSG', 'Students study NLP methods for socially relevant applications, examining how language technologies can support communication, access and analysis in public-interest domains.'),
  ('4343PROFX', 'Students learn how mathematical proofs can be represented and checked by machines, studying formal proof systems and proof assistants for reliable reasoning.'),
  ('4343QUALG', 'Students study quantum computation and key quantum algorithms, learning how this model differs from classical computing and where it may offer advantages.'),
  ('4343RECSX', 'Students learn how AI-driven recommender systems model user preferences, personalize choices and raise practical issues around data, algorithms, evaluation and impact.'),
  ('4343RINLX', 'Students learn reinforcement learning theory and algorithms, with attention to deep reinforcement learning successes in games, robotics and sequential decision-making problems.'),
  ('4343ROBO6', 'Students study modern robot architectures, sensors, actuators, navigation, mapping, manipulation, human-robot interaction and adaptive behavior in natural environments.'),
  ('4343SADL6', 'Students work in groups on recent deep learning papers, replicating and extending results while learning current topics through lectures and peer presentations.'),
  ('4343SADRL', 'Students study recent deep reinforcement learning papers, replicate results in small groups, present progress and write a research-style report.'),
  ('4343SMTAI', 'Students investigate trustworthy AI topics such as robustness, verification, explainability, bias and privacy through recent research papers, presentations and group reports.'),
  ('4343SNACS', 'Students study network science for social and technical systems, covering network models, algorithms, visualization, epidemics, pattern detection and computational complexity.'),
  ('4343SPDSX', 'Students learn how data science supports sports analysis, covering training optimization, injury prevention, tactical decisions, time series, feature construction and subgroup discovery.'),
  ('4343SWVRX', 'Students study formal verification, especially model checking, to prove correctness of software and hardware systems beyond what testing alone can guarantee.'),
  ('4343SYSSS', 'Students study software and hardware security, covering vulnerabilities, mitigations, secure development, processor-level attacks, roots of trust and research-oriented group projects.'),
  ('4343TXTMX', 'Students learn text mining foundations and applications, including text representation, classification, annotation, transformer models, information extraction, topic modeling, summarization and sentiment analysis.'),
  ('4343URBC6', 'Students study urban computing with spatio-temporal data mining, learning how computing methods address mobility, traffic, pollution and environmental challenges.'),
  ('4373MUMAB', 'Students use mathematical and computational models to study biological systems across scales, connecting biological questions with applied mathematical problem-solving.'),
  ('4383ARCR3', 'Students explore emotional, creative, curious and lifelike robots, then build an artificial creature that makes a chosen human-like quality tangible.'),
  ('4383COMCR', 'Students explore computational models of creativity, creative agents, co-creative systems, evaluation methods and philosophical questions through literature discussions and a practical project.'),
  ('4383HICNM', 'Students compare human cognition with intelligence in nature and machines, reflecting on recent AI advances and what they imply for understanding minds.'),
  ('4383VGFR6', 'Students learn to design and conduct research with video games or interactive experiences, combining game studies, development practice and applied research design.'),
  ('4433COMST', 'This course introduces computational statistics through numerical methods, algorithms, simulation and mathematical techniques for solving statistical problems in practice.'),
  ('4433DATVI', 'Students learn how to design effective statistical visualizations, evaluate graphical choices and communicate data patterns clearly across applied research contexts.'),
  ('4433EXPDA', 'Students learn exploratory data analysis methods for high-dimensional datasets, using visualization and statistical techniques to uncover relationships beyond simple two-variable plots.'),
  ('4433HDDAN', 'Students analyze high-dimensional biological and biomedical data, learning statistical methods for many variables, small sample sizes and complex dependency structures.'),
  ('4433LGMO6', 'Students study linear regression, analysis of variance and generalized linear models for explaining how predictors influence quantitative or categorical response variables.'),
  ('4433STATG', 'Students model genetic data for life science applications, studying pedigrees, linkage, heritability, association studies, Mendelian randomization and gene expression analysis.'),
  ('4433STATL', 'Students learn supervised and unsupervised statistical learning methods, including regression, classifiers, clustering, dimension reduction, model selection and evaluation.'),
  ('4609COMNWY', 'Students study complex networks across physics, mathematics and computer science, covering real-world network properties, models, algorithms, visualization, epidemics and computational complexity.')
)
update public.courses c
set description = s.description
from summaries s
where c.code = s.code;
