with descriptions (code, description) as (values
  ('4032NLP6X', 'Core NLP methods connect computer science, linguistics and AI, with attention to how modern systems process and generate language.'),
  ('4343ADVDX', 'Modern data mining methods cover massive datasets, streaming data, similarity search, anomaly detection, clustering, recommender systems and dimensionality reduction.'),
  ('4343AIART', 'Generative AI meets artistic practice through questions about creativity, authorship, aesthetics, ethics and the changing role of machines in art.'),
  ('4343AISOC', 'AI is examined through social, political, ethical and environmental lenses, then applied to real domains in a speculative hands-on project.'),
  ('4343APQALY', 'Practical quantum algorithm design focuses on chemistry, physics, machine learning and the error correction methods needed for noisy devices.'),
  ('4343AUDIO', 'Speech recognition, audio synthesis and content-based retrieval are explored through lectures, workshops, literature study, presentations and project demos.'),
  ('4343AUTMX', 'AutoML methods show how algorithms and hyperparameters can be selected to improve predictive performance on new datasets.'),
  ('4343BAYOP', 'Bayesian optimization focuses on expensive black-box functions, Gaussian processes, acquisition functions, noisy observations, constraints and Python applications.'),
  ('4343BICAI', 'Efficient AI is approached through brain-inspired ideas such as compression, quantization, neuromorphic computing and low-power machine learning hardware.'),
  ('4343BIOMD', 'Biological processes are modeled with formal computational frameworks such as Boolean networks and Petri nets, supported by tool practice and project work.'),
  ('4343BSCC4', 'Realistic company cases bring together earlier business and IT knowledge through problem analysis and practical recommendations for management.'),
  ('4343BSCSM', 'Cybersecurity is treated as a management problem, covering organizational risk, governance, policy and the business impact of ICT security decisions.'),
  ('4343BSDPM', 'Digital-era policy making is studied through data readiness, governance infrastructure, accountability and technology-driven public innovation.'),
  ('4343BSEA6', 'Enterprise architecture methods help connect business processes, information systems, principles and implementation choices into coherent organizational designs.'),
  ('4343BSGBG', 'A CIO-focused simulation connects company management, ICT strategy, business decisions and their organizational consequences.'),
  ('4343BSICT', 'ICT enabled process innovation focuses on process thinking and the redesign of business activities through information technologies.'),
  ('4343BSMAC', 'Business Studies thesis preparation covers research topics, host organizations, supervision, project execution and thesis expectations.'),
  ('4343BSMDS', 'Conceptual modeling and model-driven engineering are used to design large enterprise information systems with clear notations, principles and tools.'),
  ('4343BSMLB', 'Machine learning for business analytics turns organizational data into predictive insights for decisions in business and government contexts.'),
  ('4343BSMSE', 'Software evolution is studied through maintenance, legacy systems, technical debt and strategies for managing long-term change.'),
  ('4343BSRGD', 'Data governance for AI centers on data quality, control, regulation and the social and business challenges of responsible data use.'),
  ('4343BSRPA', 'Public-sector ICT projects are analyzed through public administration theory, leadership, regulation, collaboration, governance and data-era policy challenges.'),
  ('4343BSSDP', 'Software product management connects product strategy, lifecycle management, Scrum, project planning, quality, risk and user expectations.'),
  ('4343CICSX', 'Causal inference for machine learning covers structural causal models, potential outcomes, interventions, counterfactuals and data-driven discovery methods.'),
  ('4343CIMTO', 'Computational imaging and tomography connect physical measurement models, inverse problems, algorithms, high-performance computing and research literature.'),
  ('4343CLCMX', 'Cloud computing is covered from infrastructure and deployment models to scalability, resource management, cloud programming and hands-on platform assignments.'),
  ('4343CMS6X', 'Computational models and programming language semantics are studied through functional, probabilistic and categorical perspectives, Haskell assignments and research work.'),
  ('4343CRYPE', 'Secure implementation of cryptographic algorithms is studied across hardware and software, with attention to performance, resources, energy use and side-channel risks.'),
  ('4343DASPR', 'Fieldlab data problems drive work from problem exploration and data quality assessment to solution design and applied data science practice.'),
  ('4343DDORW', 'Real-world optimization problems are modeled with constraints, uncertainty and data, connecting theory to practical decision-making applications.'),
  ('4343DISYX', 'Distributed systems principles are linked to social networks, government services and streaming platforms, with attention to reliability and coordination.'),
  ('4343EMBSS', 'Embedded systems are studied where software interacts tightly with physical environments, from appliances and medical devices to portable systems.'),
  ('4343EVALX', 'Evolutionary algorithms search for solutions through population-based variation and selection, with applications to complex optimization problems.'),
  ('4343FSWT6', 'Software testing foundations explain why faults arise, how testing reveals failures and how systematic techniques improve reliability.'),
  ('4343HIPX6', 'High-performance computing covers supercomputer architectures, distributed and shared-memory programming, GPU optimization and performance-aware scientific computing.'),
  ('4343INDLX', 'Neural network concepts, deep learning architectures and computer vision applications are combined with theory and practical work on modern deep models.'),
  ('4343INFRX', 'Search and information access technologies are studied from classical retrieval models to large language model contexts and practical retrieval challenges.'),
  ('4343IRPRJ', 'A smaller bioinformatics research project builds experience with scientific research, project planning, innovation and reporting before the master thesis.'),
  ('4343ITDM6', 'Information-theoretic data mining focuses on principled models for discovering structure, exploratory analysis and interpretable pattern discovery.'),
  ('4343MACLA', 'Regular master class meetings support thesis work through discussions of research progress, academic practice and thesis-related topics.'),
  ('4343MGAIX', 'Modern game AI methods cover algorithms used in games and robotics, with emphasis on reinforcement learning for realistic game-playing problems.'),
  ('4343MMAV6', 'Microscopy applications connect image formation, image processing methods and practical analysis of scientific image data.'),
  ('4343MMEBX', 'Multimodal modeling for biodiversity monitoring combines images, audio and biological measurements to improve automated ecological analysis.'),
  ('4343MMSY6', 'Multimedia systems are studied across storage, processing, transmission and presentation of media, connecting system design with practical applications.'),
  ('4343MOADX', 'Advanced optimization combines constraints, multiple objectives, computational methods, decision analysis and applied mathematics.'),
  ('4343MRP22', 'The final CS and Business Studies thesis project combines original research with a business research internship.'),
  ('4343MRP30', 'The Education and Science Communication thesis project centers on original Computer Science research under academic supervision.'),
  ('4343MRP42', 'The main Computer Science thesis project forms the final stage of the MSc program through original supervised research.'),
  ('4343NLPSG', 'NLP for social good examines how language technologies can support communication, access and analysis in public-interest domains.'),
  ('4343PROFX', 'Formal proof systems and proof assistants show how mathematical proofs can be represented and checked by machines.'),
  ('4343QUALG', 'Quantum computation and key quantum algorithms are introduced through their differences from classical computing and possible advantages.'),
  ('4343RECSX', 'AI-driven recommender systems model user preferences, personalize choices and raise practical questions about data, algorithms, evaluation and impact.'),
  ('4343RINLX', 'Reinforcement learning theory and algorithms are linked to deep reinforcement learning results in games, robotics and sequential decision-making.'),
  ('4343ROBO6', 'Modern robotics covers architectures, sensors, actuators, navigation, mapping, manipulation, human-robot interaction and adaptive behavior.'),
  ('4343SADL6', 'Recent deep learning papers are replicated and extended in groups, with current topics introduced through lectures and peer presentations.'),
  ('4343SADRL', 'Recent deep reinforcement learning papers are studied through replication work, group presentations and a research-style report.'),
  ('4343SMTAI', 'Trustworthy AI topics include reliability, verification, explainability, bias and privacy, explored through recent papers, presentations and group reports.'),
  ('4343SNACS', 'Network science for social and technical systems covers models, algorithms, visualization, epidemics, pattern detection and computational complexity.'),
  ('4343SPDSX', 'Sports data science connects data methods to training optimization, injury prevention, tactical decisions, time series and subgroup discovery.'),
  ('4343SWVRX', 'Formal verification, especially model checking, is used to prove correctness of software and hardware systems beyond what testing alone can guarantee.'),
  ('4343SYSSS', 'Software and hardware security topics include vulnerabilities, mitigations, secure development, processor-level attacks, roots of trust and research projects.'),
  ('4343TXTMX', 'Text mining covers representation, classification, annotation, transformer models, information extraction, topic modeling, summarization and sentiment analysis.'),
  ('4343URBC6', 'Urban computing applies spatio-temporal data mining to mobility, traffic, pollution and environmental challenges.'),
  ('4373MUMAB', 'Mathematical and computational models are used to study biological systems across scales and connect biological questions with applied problem-solving.'),
  ('4383ARCR3', 'Emotional, creative, curious and lifelike robots are explored through the design of an artificial creature with a tangible human-like quality.'),
  ('4383COMCR', 'Computational creativity covers creative agents, co-creative systems, evaluation methods and philosophical questions through literature discussions and a project.'),
  ('4383HICNM', 'Human cognition is compared with intelligence in nature and machines, including what recent AI advances imply for understanding minds.'),
  ('4383VGFR6', 'Research with video games and interactive experiences combines game studies, development practice and applied research design.'),
  ('4433COMST', 'Computational statistics is introduced through numerical methods, algorithms, simulation and mathematical techniques for solving statistical problems in practice.'),
  ('4433DATVI', 'Effective statistical visualization is treated as a design problem, with attention to graphical choices and clear communication of data patterns.'),
  ('4433EXPDA', 'Exploratory data analysis uses visualization and statistical techniques to uncover relationships in high-dimensional datasets.'),
  ('4433HDDAN', 'High-dimensional biological and biomedical data analysis focuses on many variables, small sample sizes and complex dependency structures.'),
  ('4433LGMO6', 'Linear regression, analysis of variance and generalized linear models are used to explain quantitative and categorical response variables.'),
  ('4433STATG', 'Genetic data modeling covers pedigrees, linkage, heritability, association studies, Mendelian randomization and gene expression analysis.'),
  ('4433STATL', 'Statistical learning covers supervised and unsupervised methods such as regression, classifiers, clustering, dimension reduction, model selection and evaluation.'),
  ('4609COMNWY', 'Complex networks are studied across physics, mathematics and computer science through real-world properties, models, algorithms, visualization and epidemics.')
)
update public.courses c
set description = d.description
from descriptions d
where c.code = d.code;
